### ISSUE TITLE
好吧，被4.2版本坑了5个小时的我给大家提个醒

### ISSUE THREAD

**Issue by choujimmy** [cnpm/cnpm#100]
-前提
react的ssr(server side render)工程，使用了[webpack-isomorphic-tools](https://github.com/halt-hammerzeit/webpack-isomorphic-tools)管理服务端中出的资源

-现象
webpack-assets.json文件不能正确生成assets，报asset not found错误，服务端中出dom和客户端dom结构checksum不一致。

-原因
所有通过WebpackIsomorphicToolsPlugin.style_loader_filter方法filter的资源返回false，style_loader_filter中是这样写的：

`return regular_expression.test(module.name) && module.name.split('!')[0].indexOf('/~/css-loader') >= 0;`

通过cnpm 4.2的npminstall方式安装的依赖，这里的module.name实际上是`.npminstall/css-loader`等等，符合不了这个条件判断

**Comment by fengmk2** [comment]
`'/~/css-loader'` 这个判断在 `node_modules/css-loader` 下也无法通过吧

**Comment by choujimmy** [comment]
`./~/css-loader?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash
:base64:5]!./~/postcss-loader!./~/sass-loader?outputStyle=expanded&sourceMap!./src/common/views/App/App.scss`

这是使用npm 3.8.3 install后的webpack的loader的module.name

**Comment by dead-horse** [comment]
cnpm4 的这个 module.name 打印一下看看？

**Comment by choujimmy** [comment]
`./~/.npminstall/css-loader/0.23.1/css-loader?modules&importLoaders=2&sourceMap&loca
lIdentName=[local]___[hash:base64:5]!./~/.npminstall/postcss-loader/0.8.2/postcss-loader!./~/.npminstall/sass-loader/3.2.0/sas
s-loader?outputStyle=expanded&sourceMap!./src/common/views/App/App.scss`

OS X 10.11.4

**Comment by fengmk2** [comment]
看来得去给 webpack-isomorphic-tools 提交一个 pr 支持了。

**Comment by choujimmy** [comment]
突然由这个想到cnpm 4.2版本这种依赖包组织方式的另外一个问题，**暂时未验证，先抛出来**

例如我有两个工程：
-一个是ui组件的工程（后面以u代替）,该项目peerDependencies和devDependencies包含react模块
-另外一个是依赖该ui组件的web工程（后面以w代替），该项目dependencies包含react模块

在development期间，我们会想u模块的每个变动都反映在w模块中，我会在u模块的本地根目录npm link，在w模块引入npm link u，这样在w运行的时候会有一个react的错误，即指向了两个不同的react模块副本，具体的错误内容我忘记了

之前我们要解决这个问题有两个办法，一个是在w模块的根目录之行npm dedupe扁平化他的依赖包，第二个办法是在w模块的webpack配置中使用resolve alias react强制指定react模块的所在路径

说了一大通，我想表达的是现在cnpm 4.2的这种依赖包组织方式是否会造成上面提到的**指向了两个不同的react模块副本问题**，因为根目录下的node_modules目录里面的每个包实际上都相当于是npm link过来的

**Comment by fengmk2** [comment]
npm 本身就是支持同一个模块多个版本的存在的，也是它与其他代码库仓库最大的区别。

**Comment by fengmk2** [comment]
https://github.com/halt-hammerzeit/webpack-isomorphic-tools/pull/67

**Comment by fengmk2** [comment]
@choujimmy 等 webpack-isomorphic-tools 如何被合并发布了，就没问题了。

**Comment by fengmk2** [comment]
@choujimmy webpack-isomorphic-tools@2.2.45 已经发布了。
