### ISSUE TITLE
全局安装 strongloop出错(4.2版本出错，3.4.1OK)

### ISSUE THREAD

**Issue by pluswave** [cnpm/cnpm#102]
cnpm install -g strongloop 

```
install sl-blip from remote http://blip.strongloop.com/strongloop@6.0.0, may be very slow, please keep patience
[strongloop@6.0.0] install error: Error: ENOTEMPTY: directory not empty, rmdir '/Users/zzb/nvm/versions/node/v4.4.2/lib/node_modules/.strongloop_npminstall/strong-pm/5.2.1/strong-pm/node_modules', parentDir: /Users/zzb/nvm/versions/node/v4.4.2/lib, remove /Users/zzb/nvm/versions/node/v4.4.2/lib/node_modules/.strongloop_npminstall/strongloop/6.0.0/strongloop
error stack: Error: ENOTEMPTY: directory not empty, rmdir '/Users/zzb/nvm/versions/node/v4.4.2/lib/node_modules/.strongloop_npminstall/strong-pm/5.2.1/strong-pm/node_modules'
    at Error (native)
Error: ENOTEMPTY: directory not empty, rmdir '/Users/zzb/nvm/versions/node/v4.4.2/lib/node_modules/.strongloop_npminstall/strong-pm/5.2.1/strong-pm/node_modules'
Error: ENOTEMPTY: directory not empty, rmdir '/Users/zzb/nvm/versions/node/v4.4.2/lib/node_modules/.strongloop_npminstall/strong-pm/5.2.1/strong-pm/node_modules'
    at Error (native)
```

**Comment by fengmk2** [comment]
> install sl-blip from remote http://blip.strongloop.com/strongloop@6.0.0, may be very slow, please keep patience

无解，直接去 strongloop 下载了。

**Comment by fengmk2** [comment]
strong-pm/5.2.1/strong-pm/package.json 无法直接 json parse

content buffer: {"type":"Buffer","data":[239,187,191,123,10,32,32,34,110,97,109,101,34,58,32,34,115,116,114,111,110,103,45,115,112,97,119,110,45,110,112,109,34,44,10,32,32,34,118,101,114,115,105,111,110,34,58,32,34,49,46,48,46,48,34,44,10,32,32,34,100,101,115,99,114,105,112,116,105,111,110,34,58,32,34,82,101,108,105,97,98,108,121,32,115,112,97,119,110,32,110,112,109,226,132,162,32,111,110,32,97,110,121,32,112,108,97,116,102,111,114,109,34,44,10,32,32,34,109,97,105,110,34,58,32,34,105,110,100,101,120,46,106,115,34,44,10,32,32,34,114,101,112,111,115,105,116,111,114,121,34,58,32,123,10,32,32,32,32,34,116,121,112,101,34,58,32,34,103,105,116,34,44,10,32,32,32,32,34,117,114,108,34,58,32,34,104,116,116,112,115,58,47,47,103,105,116,104,117,98,46,99,111,109,47,115,116,114,111,110,103,108,111,111,112,47,115,116,114,111,110,103,45,115,112,97,119,110,45,110,112,109,46,103,105,116,34,10,32,32,125,44,10,32,32,34,97,117,116,104,111,114,34,58,32,34,66,101,114,116,32,66,101,108,100,101,114,32,60,98,101,114,116,98,101,108,100,101,114,64,103,109,97,105,108,46,99,111,109,62,34,44,10,32,32,34,108,105,99,101,110,115,101,34,58,32,123,10,32,32,32,32,34,110,97,109,101,34,58,32,34,68,117,97,108,32,77,73,84,47,83,116,114,111,110,103,76,111,111,112,34,44,10,32,32,32,32,34,117,114,108,34,58,32,34,104,116,116,112,115,58,47,47,103,105,116,104,117,98,46,99,111,109,47,115,116,114,111,110,103,108,111,111,112,47,108,111,111,112,98,97,99,107,47,98,108,111,98,47,109,97,115,116,101,114,47,76,73,67,69,78,83,69,34,10,32,32,125,44,10,32,32,34,98,117,103,115,34,58,32,123,10,32,32,32,32,34,117,114,108,34,58,32,34,104,116,116,112,115,58,47,47,103,105,116,104,117,98,46,99,111,109,47,115,116,114,111,110,103,108,111,111,112,47,115,116,114,111,110,103,45,115,112,97,119,110,45,110,112,109,47,105,115,115,117,101,115,34,10,32,32,125,44,10,32,32,34,104,111,109,101,112,97,103,101,34,58,32,34,104,116,116,112,115,58,47,47,103,105,116,104,117,98,46,99,111,109,47,115,116,114,111,110,103,108,111,111,112,47,115,116,114,111,110,103,45,115,112,97,119,110,45,110,112,109,34,10,125,10]}

**Comment by fengmk2** [comment]
@pluswave 请重新安装一下 cnpm 即可解决。
