### ISSUE TITLE
[建议] 遵循 npm 3 的新机制更新 cnpm

### ISSUE THREAD

**Issue by jk2K** [cnpm/cnpm#106]
`Npm` 3 解决了依赖重复的问题，避免了 `WebStorm` 重复索引文件，大大提高了性能，避免 `WebStorm` 输入时`Code Completion`卡顿的问题

详情可以了解这篇博文 [How npm 3 solves WebStorm's performance issues](https://www.themarketingtechnologist.co/how-npm3-will-saves-webstorms-life/)

使用`npm 3.8.6`安装依赖的结果如下
![image](https://cloud.githubusercontent.com/assets/4025839/14848309/a276b6d8-0c9f-11e6-902b-c2ef2d683655.png)

使用`cnpm`安装相同依赖的结果如下
![image](https://cloud.githubusercontent.com/assets/4025839/14848327/add12eaa-0c9f-11e6-9bba-704243d74f24.png)

建议用户采用如下方式使用淘宝`NPM`镜像
```bash
alias cnpm="npm --registry=https://registry.npm.taobao.org \
--cache=$HOME/.npm/.cache/cnpm \
--disturl=https://npm.taobao.org/dist \
--userconfig=$HOME/.cnpmrc"

# Or alias it in .bashrc or .zshrc
$ echo '\n# alias for cnpm\nalias cnpm="npm --registry=https://registry.npm.taobao.org \
  --cache=$HOME/.npm/.cache/cnpm \
  --disturl=https://npm.taobao.org/dist \
  --userconfig=$HOME/.cnpmrc"' >> ~/.zshrc && source ~/.zshrc
```

**Comment by alsotang** [comment]
cnpm -v 看看？

2016-04-27 17:52 GMT+08:00 Meng Ye <notifications@github.com>:

**Comment by jk2K** [comment]
`npm install -g cnpm --registry=https://registry.npm.taobao.org`
通过这个命令安装的，我已经卸载了，应该是`4.2.0`

可以通过这个`package.json`来测试
```json
{
  "dependencies": {
    "babel-register": "^6.7.2",
    "babel-runtime": "^6.6.1",
    "koa": "^2.0.0",
    "koa-nunjucks-2": "^3.0.0-alpha.2",
    "koa-router": "^7.0.1",
    "koa-static": "^3.0.0"
  },
  "devDependencies": {
    "babel-plugin-transform-runtime": "^6.7.5",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-stage-3": "^6.5.0"
  }
}
```

**Comment by GilbertSun** [comment]
同意，最近发现用 cnpm 安装依赖后经常会导致webstorm 卡死

**Comment by fengmk2** [comment]
@atian25 可以给一下 webstorm 卡死的原因和解决方案。

**Comment by atian25** [comment]
卡死的原因我没细研究, 猜测是文件太多了.

解决方案目前是:
- node_module 目录设置  mark as exclude
- 然后需要索引的库, 在 libraries 里面单独添加

**Comment by dead-horse** [comment]
卡死的原因可能是 Link 导致的循环依赖？

**Comment by atian25** [comment]
有可能

**Comment by alsotang** [comment]
我用着 webstorm，不过我安装东西一直是用 npm3 来安装，所以也不懂 npminstall 这边的情况。

2016-04-29 13:02 GMT+08:00 TZ | 天猪 <notifications@github.com>:

**Comment by fengmk2** [comment]
@alsotang 你还没深度用 react，没有太大模块使用 webpack。。

**Comment by alsotang** [comment]
我不用 react。。。我用 vue.js 的。。。

2016-04-29 14:35 GMT+08:00 fengmk2 <notifications@github.com>:

**Comment by WittBulter** [comment]
原来node_modules几十个依赖cnpm装的确有这个问题,特别是和babel有关的,重复依赖很严重,webstorm几乎打不开.换了npm3之后webstorm才能正常运行.

**Comment by zeroweb** [comment]
有没有具体的操作步骤啊，刚开始用webstorm

**Comment by agileago** [comment]
这个问题结果如何？项目只要用cnpm i装完依赖后，webstorm打开必卡死

**Comment by ibigbug** [comment]
webstorm ignore node_moduels

**Comment by fengmk2** [comment]
有一个比较好的方式解决，如果当前目录有 .idea 目录，则代表是 webstorm 项目，然后给 `.idea/modules.xml` 的 modules 节点加上 `<module fileurl="file://$PROJECT_DIR$/.idea/npminstall.iml" filepath="$PROJECT_DIR$/.idea/npminstall_ignore.iml" />` 配置，然后自动生成 `npminstall_ignore.iml` 配置文件

```xml
<?xml version="1.0" encoding="UTF-8"?>
<module type="WEB_MODULE" version="4">
  <component name="NewModuleRootManager">
    <content url="file://$MODULE_DIR$">
      <excludeFolder url="file://$MODULE_DIR$/node_modules" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
  </component>
</module>
```

缺点就是入侵性太大。

**Comment by fengmk2** [comment]
已经给 webstorm 提过了，大家 exclude node_modules 吧 https://youtrack.jetbrains.com/issue/WEB-20705

**Comment by mrdulin** [comment]
vscode 也出现了用cnpm安装依赖，编辑器卡死的问题，并且command + p查找文件，由于很慢导致autocomplete菜单出不来的问题呢。把node_modules移动到项目外面，就好了。而且并行的两个项目，一个用的是npm3, 一个用的是cnpm4.1，npm3的没问题，所以初步怀疑是cnpm的问题。

**Comment by dead-horse** [comment]
这个问题是由于 cnpm 的 link 方式引起的，通用解决方案是让编辑器不要去索引 node_modules 目录，cnpm 暂时不会改变 link 的安装方式，如果想用 npm 的安装方式，可以安装最新版的 cnpm，并用 `cnpm install --by=npm` 来安装模块

**Comment by dead-horse** [comment]
这个问题是由于 cnpm 的 link 方式引起的，通用解决方案是让编辑器不要去索引 node_modules 目录，cnpm 暂时不会改变 link 的安装方式，如果想用 npm 的安装方式，可以安装最新版的 cnpm，并用 `cnpm install --by=npm` 来安装模块

**Comment by mrdulin** [comment]
@dead-horse 哦，原来如此。谢谢

**Comment by atian25** [comment]
@mrdulin vscode 默认的 settings.json 是禁止搜索 node_modules 的, 你是开启了这个配置么?
```js
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true
  },

  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/node_modules/**": true
  },
```

**Comment by think2011** [comment]
webstorm 直接卡死 +1

**Comment by dead-horse** [comment]
https://github.com/coolme200/webstorm-disable-index @think2011
