### ISSUE TITLE
error install @angular2-material/progress-bar

### ISSUE THREAD

**Issue by thunderrun** [cnpm/cnpm#107]
when i run 
`cnpm install -S @angular2-material/progress-bar`
I got the following error
```bash
Error: GET https://registry.npm.taobao.org/@angular2-material%2Fprogress-bar/* response 404 status
Error: GET https://registry.npm.taobao.org/@angular2-material%2Fprogress-bar/* response 404 status
    at get (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/get.js:55:11)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
but works well running
`npm install -S @angular2-material/progress-bar -registry https://registry.npmjs.org/`

It seems that *cnpm* is not able to sync this module or let user to install from official *npm* registry.

**Comment by fengmk2** [comment]
Please try again

**Comment by thunderrun** [comment]
it's working well now, thanks for fixing

**Comment by thunderrun** [comment]
encounter the same error while install `@angular/platform-server`, maybe `cnpm` won't sync modules which have `@` in their name ?

**Comment by fengmk2** [comment]
@thunderrun cnpmjs.org sync packages using this npm registry api http://registry.npmjs.org/-/all/static/today.json. And I search `@angular/platform-server` keyword but it not exists.

**Comment by fengmk2** [comment]
@thunderrun you can sync by yourself.

```bash
$ cnpm sync @angular/platform-server
```

**Comment by fengmk2** [comment]
I create a issue to npm registry team https://github.com/npm/registry/issues/13
