### ISSUE TITLE
安装ionic@beta报错。

### ISSUE THREAD

**Issue by DarrenHou1993** [cnpm/cnpm#108]
![image](https://cloud.githubusercontent.com/assets/9291785/15008229/69b7ae66-1211-11e6-92dd-6e83fe21da08.png)

**Comment by xylinq** [comment]
1.7.14 也是一样的错误

**Comment by dead-horse** [comment]
cnpm 版本是多少

**Comment by xylinq** [comment]
我的是 4.2.0

**Comment by dead-horse** [comment]
奇怪，我的安装 1.7.14 正常，看 @DarrenHou1993 的报错日志是下载的包校验和不对

**Comment by dead-horse** [comment]
@xylinq 截图看一下？

**Comment by dead-horse** [comment]
node 版本和操作系统也发一下

**Comment by xylinq** [comment]
![1 pic_hd](https://cloud.githubusercontent.com/assets/1905319/15011837/9b0b66be-1226-11e6-87f8-4e86f7982ab2.jpg)

node 版本是 v5.0.0  操作系统是 Mac OS X 10.11.4

**Comment by fengmk2** [comment]
@xylinq @DarrenHou1993 确保没有使用代理吧?

**Comment by fengmk2** [comment]
```
cnpm i ionic@beta --no-cache
[ionic@beta] installed at node_modules/.npminstall/ionic/2.0.0-beta.25/ionic (0 packages, use 27s, speed 897.26kB/s, json 30.26kB, tarball 23.85MB)
All packages installed (1 packages installed from npm registry, use 27s, speed 896.9kB/s, json 1(30.26kB), tarball 23.85MB)
mk2@/tmp node@v4.4.3 
👿  cnpm -v
4.2.0
```

我本地试了一下是 ok 的

**Comment by fengmk2** [comment]
请使用 `DEBUG=npminstall* cnpm i ionic@1.7.14` 命令将 debug 信息输出，将出错前后的日志100行贴上来

**Comment by fengmk2** [comment]
我怀疑你们下载这个包没下载下来

```json
"dist": {
"shasum": "af493d5df4688d917d778b0934d1739b9be6efe6",
"size": 26842945,
"noattachment": false,
"tarball": "http://registry.npm.taobao.org/ionic/download/ionic-1.7.14.tgz"
},
```

**Comment by fengmk2** [comment]
@xylinq 试试使用以下命令手动测试一下，看看sha1最终是多少

```bash
wget http://registry.npm.taobao.org/ionic/download/ionic-1.7.14.tgz
shasum ionic-1.7.14.tgz
```

**Comment by DarrenHou1993** [comment]
请问一下大家node的版本用的多少。我现在是5.6.0。 感觉是不是应该切回去到4.x比较好？

**Comment by DarrenHou1993** [comment]
@dead-horse 大神，刚看了一下你的资料。koa也是你参与的。请受小弟一拜。

**Comment by xylinq** [comment]
@fengmk2 我加了 --no-cache 参数后就安装成功了，看来之前应该是包没有下载成功，多谢你的帮助！

**Comment by fengmk2** [comment]
能帮忙看看你们下载这个 tgz包的下载速度么？

**Comment by xylinq** [comment]
![2 pic_hd](https://cloud.githubusercontent.com/assets/1905319/15065475/ab23c40c-1392-11e6-9c2b-d524ff634f0b.jpg)

**Comment by fengmk2** [comment]
@xylinq 速度还好的。

**Comment by fengmk2** [comment]
@DarrenHou1993 我一般只用 LTS 的版本。

**Comment by DarrenHou1993** [comment]
@fengmk2  谢谢大神指点。方便加个好友吗？有时候人生的道路需要点指引。以免少走弯路呀。

**Comment by fengmk2** [comment]
@DarrenHou1993 可以的，多提交 PR。
