### ISSUE TITLE
exec('cnpm install --save ' + getInstallPackage(rnPackage), function(e, stdout, stderr) {

### ISSUE THREAD

**Issue by cooliean** [cnpm/cnpm#111]
exec('npm install --save ' + getInstallPackage(rnPackage), function(e, stdout, stderr) {

exec('cnpm install --save ' + getInstallPackage(rnPackage), function(e, stdout, stderr) {

这两个命令出事换出来的Reactnative项目差很远为什么呢，甚至不能运行。

**Comment by fengmk2** [comment]
RTFM https://github.com/cnpm/npminstall#different-with-npm

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpm/issues/94 react-native 目前不行。
