### ISSUE TITLE
安装babel-polyfill报错，有人说可能是node版本问题，是不是真的？

### ISSUE THREAD

**Issue by raoenhui** [cnpm/cnpm#115]
![image](https://cloud.githubusercontent.com/assets/14011130/15627662/9f9b1062-251d-11e6-9a12-8fcefc375cd1.png)

但是直接npm安装是可以成功的，有人说可能是node版本问题，是不是真的？
我的node版本好如下图
![image](https://cloud.githubusercontent.com/assets/14011130/15627667/c152cccc-251d-11e6-9ef2-020ee1a270ef.png)
![image](https://cloud.githubusercontent.com/assets/14011130/15627669/c7d6fe74-251d-11e6-839c-1adfe8f32f32.png)

**Comment by ibigbug** [comment]
是真的。

把 node 版本升级到 4.0 以上，推荐 4.3.2。

`npm WARN engine cnpm@4.2.0: wanted: {"node":">= 4.3.2"} (current: {"node":"4.0.0","npm":"2.14.2"})`

**Comment by fengmk2** [comment]
node 必须 >= 4.0.0
