### ISSUE TITLE
使用 cnpm 安装某个 app 依赖包时出现了无限循环创建子目录...

### ISSUE THREAD

**Issue by sagan** [cnpm/cnpm#117]
使用最新版 cnpm 安装 [relay](https://github.com/facebook/relay) 里的一个示例应用的依赖包时, 出现了无限循环创建子目录的问题...

cd relay-master/examples/relay-treasurehunt
cnpm install

装了一半发现进度不动了, 放弃. 打算删除 relay-master 目录时发现删不掉, 系统报 "路径过长"错误, 到资源管理器里一看吓了一跳, cnpm 在relay-treasurehunt/node_modules 这个目录下无限循环创建了 N 个子目录...

![screenshot 2016-05-29 13 15 21](https://cloud.githubusercontent.com/assets/1836852/15631533/50e32d72-25a1-11e6-9bc4-61d01aeaac59.png)

![screenshot 2016-05-29 13 21 01](https://cloud.githubusercontent.com/assets/1836852/15631535/50e9b34a-25a1-11e6-9072-cfb6254c417c.png)

无奈用 DelinvFile 这个工具强行删除 relay-master 这个文件夹, 工具跑了十几分钟, 已经删除了超过了100万个目录, 还在继续删除 ing...

![screenshot 2016-05-29 13 15 30](https://cloud.githubusercontent.com/assets/1836852/15631534/50e57e24-25a1-11e6-8422-87fef546a8e7.png)

 
环境:
windows 7 x64
node.js v6.2.0 x64
cnpm 最新版

**Comment by fengmk2** [comment]
里面有一个 preinstall，这个是使用 npm install 的，你得去改里面的 npm install 为 cnpm install

```
{
  "private": true,
  "scripts": {
    "start": "babel-node ./server.js",
    "update-schema": "babel-node ./scripts/updateSchema.js",
    "preinstall": "cd ../.. && npm install --ignore-scripts && cd scripts/babel-relay-plugin && npm install --ignore-scripts"
  },
```

**Comment by fengmk2** [comment]
npminstall 还得支持一下 `--ignore-scripts`，我先改改。

**Comment by fengmk2** [comment]
`ignore-scripts` 已经支持了

**Comment by fengmk2** [comment]
回去 gitlab 下载 bin 文件，需要做一下镜像同步 https://github.com/flowtype/flow-bin/blob/master/lib/index.js#L14

**Comment by lanten** [comment]
![image](https://user-images.githubusercontent.com/16203518/32898308-c17c6eb8-cb22-11e7-9483-e418058df505.png)

+1
也是一个无限循环的文件夹
我忘记是不是用cnpm装的了。。。
完全删不掉，已经死机过一次了，求问有没有什么解决方案 ？
