### ISSUE TITLE
cnpm login 会添加用户

### ISSUE THREAD

**Issue by robin22333** [cnpm/cnpm#119]
我搭建了一个私有的 cnpmjs.org，cnpm 设置 registry 为自己搭建的仓库地址后，cnpm login 随便输入用户名密码就会给我在数据库里添加一个 user，如果用户名存在密码错误才会报登录失败。我看了下日志，发现每次 login 都会走

```js
app.put('/-/user/org.couchdb.user::name', addUser);
```

这个路由，不知道这是 bug，还是我需要相关配置呢？

**Comment by alsotang** [comment]
官方也是这样的吧？

在 2016年5月31日 上午10:08，罗斌 <notifications@github.com>写道：

**Comment by robin22333** [comment]
@alsotang 这样啊。。。感觉有点奇怪。感谢回复。

**Comment by fengmk2** [comment]
第一次 login 就是注册。
