### ISSUE TITLE
Error while installing dtrace-provider

### ISSUE THREAD

**Issue by XadillaX** [cnpm/cnpm#124]
`postinstall` in dtrace-provider uses an envrionment `npm_execpath`.

**Comment by dead-horse** [comment]
装最新版

**Comment by dead-horse** [comment]
重新安装一下 cnpm

**Comment by XadillaX** [comment]
-. - 原来已经修好了啊，我还准备提 pr 呢

**Comment by XadillaX** [comment]
不对啊，还是有这个问题

**Comment by XadillaX** [comment]
![image](https://cloud.githubusercontent.com/assets/2842176/16372135/80f6f55a-3c7d-11e6-99f3-990be47f506f.png)

其中 `Path must be a string` 就是因为找不到 `env.npm_execpath`

**Comment by dead-horse** [comment]
版本？

**Comment by dead-horse** [comment]
主要是看 cnpm 依赖的 npminstall 的版本

**Comment by XadillaX** [comment]
`npminstall` 是 1.10.1，果然落后了，我更新试试看。
