### ISSUE TITLE
Global package：Error: EACCES: permission denied

### ISSUE THREAD

**Issue by muhonglong** [cnpm/cnpm#126]
通过`sudo cnpm i -g gulp-cli`安装gulp工具，在非sudo环境中`gulp --version`报出错误：

> fs.js:549
> return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
>                        ^
> 
> Error: EACCES: permission denied, open '/opt/node-v4.4.7/lib/node_modules/.gulp-cli_npminstall/arr-> flatten/1.0.1/arr-flatten/index.js'
>     at Error (native)
>     at Object.fs.openSync (fs.js:549:18)
>     at Object.fs.readFileSync (fs.js:397:15)
>     at Object.Module._extensions..js (module.js:415:20)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/opt/node-v4.4.7/lib/node_modules/.gulp-cli_npminstall/arr-diff/2.0.0/arr-diff/index.js:10:15)
>     at Module._compile (module.js:409:26)

**Comment by dead-horse** [comment]
看一下文件的权限

**Comment by muhonglong** [comment]
Linux下，通过以下方式安装的node全局工具，文件的权限是没问题的。
`
sudo npm i -g gulp-cli --registry=https://registry.npm.taobao.org
`

cnpm在linux中安装global package的时候，可能和npm还是有差异。
