### ISSUE TITLE
最新版cnpm安装有问题

### ISSUE THREAD

**Issue by yuu2lee4** [cnpm/cnpm#127]
a包里面明明依赖b包 但是a包的node_modules下面却没有b包

win10-64bit

就是这个项目：https://github.com/nswbmw/N-club

**Comment by fengmk2** [comment]
具体哪个包没有呢？

**Comment by yuu2lee4** [comment]
koa-logger的依赖chalk
我删掉node_modules  重新cnpm i一下 现在又好了 但是有下面的提示

peerDependencies WARNING [co-supertest@0.0.10] in D:\work\N-club\node_modules\.npminstall\co-supertest\0.0.10\co-supertest requires a peer of supertest@^1.0 but none was installed
peerDependencies WARNING [mongodb-core@1.2.24] in D:\work\N-club\node_modules\.npminstall\mongodb-core\1.2.24\mongodb-core requires a peer of kerberos@~0.0 but none was installed

**Comment by fengmk2** [comment]
我测试是正常的。
