### ISSUE TITLE
vue-cli 用 cnpm install 项目会报错

### ISSUE THREAD

**Issue by Loyalsoldier** [cnpm/cnpm#128]
用 Vue-cli 初始化以 Webpack 为模板的项目（`vue init webpack test-project`）后，进入 `test-project` 目录，运行 `cnpm install` 报错。看了一下，大概是 Selenium 和 ChromeDriver 无法安装，提示哈希值不一致。估计是 cnpm 镜像上的文件跟 npm 上的不一致？

OS：Windows 10 64bit
cnpm: 最新版 v4.2.0
node: v4.4.5
npm: v2.15.5

**Comment by fengmk2** [comment]
你重新安装一下 cnpm 即可。我本地测试能够安装成功。

```
All packages installed (832 packages installed from npm registry, use 26s, speed 357.57kB/s, json 1088(5.82MB), tarball 3.32MB)
mk2@/tmp/test-project node@v6.3.1 

```

**Comment by Loyalsoldier** [comment]
一样的问题，看这里：#133
