### ISSUE TITLE
why cnpm can not run the command after installed?

### ISSUE THREAD

**Issue by geekplux** [cnpm/cnpm#134]
An error occurred for me is like this:

rubenspgcavalcante/leaflet-ant-path#13

> The common behavior of a npm module is to run command declared in the "scripts.install" property of package.json.

but `cnpm` would not run these command. probably this is cnpm's problem?

(and it seems not only the command `install`, also `prepublish`..)

**Comment by fengmk2** [comment]
Let me see

**Comment by fengmk2** [comment]
I use cnpm install success, can you reinstall cnpm yourself and try again?

```bash
ll node_modules/leaflet-ant-path/dist/
total 120
drwxr-xr-x   4 mk2  wheel    136 Aug  2 17:21 ./
drwxr-xr-x  15 mk2  wheel    510 Aug  2 17:21 ../
-rw-r--r--   1 mk2  wheel   7841 Aug  2 17:21 leaflet-ant-path.js
-rw-r--r--   1 mk2  wheel  53111 Aug  2 17:21 leaflet-ant-path.js.map
```

**Comment by geekplux** [comment]
thanks, somehow version problem..
