### ISSUE TITLE
cnpm安装gulp时会安装非常多的文件

### ISSUE THREAD

**Issue by simphp** [cnpm/cnpm#137]
如图所示，使用npm安装时只有gulp

![cnpm-bug](https://cloud.githubusercontent.com/assets/4106797/17843357/9e971a1e-685f-11e6-8bcd-b20cadc9e94a.png)

**Comment by fengmk2** [comment]
使用了 https://github.com/cnpm/npminstall ，可以详细看 https://github.com/cnpm/npminstall 的说明。

**Comment by wensonsmith** [comment]
道理是这样，但是这样看着好乱啊！！

我记得之前用 `cnpm` 会把依赖库安装到 ` .npminstall` 这个文件夹下，看着特别清爽。 

为什么要改呢？

**Comment by fengmk2** [comment]
@wensonsmith 因为很多模块依赖 npm3 的目录结构，并且是硬编码写死的，目前只能按现在这种情况调整。

如果你使用 atom，可以这样配置来忽略这个比较丑的目录。

![image](https://cloud.githubusercontent.com/assets/156269/18091547/9a352b30-6efb-11e6-8fc7-a8dd4d52d335.png)

**Comment by wensonsmith** [comment]
之前的那种目录结构很喜欢。。 因为我用的库采用之前的目录结构没有什么问题，所以想可不可以加一个配置项？或者 `cnpm install` 的时候跟上参数 ？

**Comment by alsotang** [comment]
```
alias cnpm="npm --registry=https://registry.npm.taobao.org \
--cache=$HOME/.npm/.cache/cnpm \
--disturl=https://npm.taobao.org/mirrors/node \
--userconfig=$HOME/.cnpmrc"
```

这样使用 cnpm 吧

**Comment by wensonsmith** [comment]
@alsotang  我用你给的这个命令，安装后不是之前的那种目录结构。 比如我装一个`serialport`, 之前的目录机构装完后， 在 `node_modules` 只有这一个 `serialport` 文件夹，他的依赖包什么的都是放在 `.npminstall` 下面的。 这个命令装完后，全都放在了 `node_modules` 下面。

**Comment by fengmk2** [comment]
可以用npminstall@1，它是按照npm2目录结构来的

**Comment by dead-horse** [comment]
> @alsotang 我用你给的这个命令，安装后不是之前的那种目录结构。 比如我装一个serialport, 之前的目录机构装完后， 在 node_modules 只有这一个 serialport 文件夹，他的依赖包什么的都是放在 .npminstall 下面的。 这个命令装完后，全都放在了 node_modules 下面。

npm3 就是这样的，所以要适应，以后 node 升级到 6 了就默认是 npm3 模式了，不要挣扎了。

**Comment by alsotang** [comment]
用我那个命令装出来的就是 node v6 自带的 npm 的目录结构。最正统的结构了，还想如何？

在 2016年9月2日 上午10:34，Yiyu He <notifications@github.com>写道：

**Comment by wensonsmith** [comment]
@fengmk2  明白啦，多谢！

@alsotang @dead-horse 
我不挣扎啦！ 顺应时代潮流~ 多谢两位！
