### ISSUE TITLE
cnpm 不支持 npm-shrinkwrap

### ISSUE THREAD

**Issue by ggpp224** [cnpm/cnpm#138]
用shrinkwrap锁定版本后， 用 cnpm install时并没有按npm-shrinkwrap.json中的内容来下载。比如：
`
"istanbul": {
          "version": "0.4.4",
          "from": "istanbul@0.4.4",
          "resolved": "http://172.18.22.198:7001/istanbul/download/istanbul-0.4.4.tgz",
          "dependencies": {
`

然后install后
`
{
  "name": "istanbul",
  "version": "0.4.5",
  "description": "Yet another JS code coverage tool that computes statement, line, function and branch coverage with module loader hooks to transparently add coverage when running tests. Supports all JS coverage use cases including unit tests, server side functional tests and browser tests. Built for scale",
  "keywords": [
    "coverage",
`

并没有下载指定的版本"0.4.4", 而是下载的是最新版本的"0.4.5".

而用 `npm install`就可以正确下载指定版本"0.4.4".

本地环境：

localhost:~ guopeng$ node -v
v4.4.1
localhost:~ guopeng$ npm -v
3.10.4
localhost:~ guopeng$ cnpm -v
4.3.2

**Comment by dead-horse** [comment]
https://github.com/cnpm/npminstall/issues/37
