### ISSUE TITLE
symlink 怎么破？

### ISSUE THREAD

**Issue by keyiis** [cnpm/cnpm#139]
用cnpm 安装完sequelize 后，sequelize/node_modules目录下全是symlink,这带来一个问题，如果我想复制整个项目到其它机器上，那么symlink将不能完整复制，不知是什么原因，至少在win10上是这样，不知道有什么办法可以解决这个问题？因为我的项目是使用node-webkit的，在发布给客户后，不可能让客户再去运行一遍npm install.

**Comment by dead-horse** [comment]
symlink 都是 link 到 sequelize/node_modules 目录下的，只要把整个包打进去就可以了。

**Comment by keyiis** [comment]
@dead-horse symlink用的是绝对路径，如果直接打包后到客户机解压后，symlink会失效，

**Comment by dead-horse** [comment]
记起来了，windows 不支持相对路径，那你只能用 npm 指定 registry 的方式来安装了。

**Comment by fengmk2** [comment]
只考虑了非 windows 打包复用，windows 下使用相对路径是有问题的。

**Comment by keyiis** [comment]
@dead-horse 能具体说下操作方法吗，只要能不在

**Comment by keyiis** [comment]
手机上打字不方便。只要能做程序解压狗能在客户机直接运行就可以，前提是客户机上肯定没装nod

**Comment by keyiis** [comment]
@dead-horse @fengmk2 我卸载了cnpm后再安装sequelize就没有symlink了，cnpm做了什么？

**Comment by keyiis** [comment]
此外由于symlink的问题，还会导致webpack在打包时出现循环依赖的警告。

**Comment by fengmk2** [comment]
如果你是非windows，软连接和使用tar来打包是OK的，但是windows 我这边目前无法解决。

**Comment by keyiis** [comment]
symlink是由npminstal产生的l,现在换成npm安装，虽然设置了registry，速度明显比用cnpm慢很多

**Comment by keyiis** [comment]
有些使用node-pre-gyp的包还需要打开vpn才能安装成功

**Comment by dead-horse** [comment]
没有办法，你打包的时候换 npm 吧，开发的时候还是用 cnpm 就好了

**Comment by fengmk2** [comment]
symlink 是速度优化的关键一环，去掉了就直接用 npm 吧。 https://github.com/cnpm/npminstall#different-with-npm

**Comment by fengmk2** [comment]
或者 windows 就直接回退到 npm 来安装好了。

**Comment by fengmk2** [comment]
```bash
$ cnpm i --installer=npm
```
