### ISSUE TITLE
npm v3.10.8 安装不了cnpm客户端

### ISSUE THREAD

**Issue by ggpp224** [cnpm/cnpm#140]
npm升级后，安装cnpm客户端时报错 :"uid must be an unsigned int",

npm v2 安装没这个问题。

`localhost:chanapp-doctor guopeng$ sudo npm install -g cnpm --registry=https://registry.npm.taobao.org
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cnpm" "--registry=https://registry.npm.taobao.org"
npm ERR! node v4.4.1
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cnpm" "--registry=https://registry.npm.taobao.org"
npm ERR! node v4.4.1
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
`

**Comment by fengmk2** [comment]
`npm install cnpm --registry=https://registry.npm.taobao.org` local 安装呢？
