### ISSUE TITLE
cnpm uninstall卸载一个包时，不能同时移除要卸载的包所依赖的其他包。

### ISSUE THREAD

**Issue by sdhhqb** [cnpm/cnpm#141]
从node 4.x版本升级到6.x 后，cnpm安装依赖时经常有包没有安装成功，想要卸载之后重新安装，遇到了包卸载不干净的问题。cnpm版本4.3.2 node版本6.7.0 npm版本3.10.3

比如安装cross-env这个包，会引入6个依赖包。

使用nrm切换registry为taobao镜像。依次执行npm install cross-env, npm uninstall cross-env后，安装时引入的依赖包被成功移除。效果如下图：

![npm_install](https://cloud.githubusercontent.com/assets/7730294/19218539/23c9932a-8e2f-11e6-8002-faa2522b96eb.jpg)

![npm_uninstal](https://cloud.githubusercontent.com/assets/7730294/19218525/b21becbe-8e2e-11e6-8bfb-5d05c40e0753.jpg)

依次执行cnpm install cross-env, cnpm uninstall cross-env后，安装时引入的依赖包还在目录中。

![cnpm_install](https://cloud.githubusercontent.com/assets/7730294/19218542/3855f928-8e2f-11e6-8645-6830219b8066.jpg)
![cnpm_uninstall](https://cloud.githubusercontent.com/assets/7730294/19218545/4e820944-8e2f-11e6-8c3f-7125300c56b3.jpg)

**Comment by dead-horse** [comment]
如果纠结这个就直接删除 node_modules 目录再重新安装吧，现在不会去像 npm 一样做这个分析。

**Comment by alsotang** [comment]
额。。。原来还有 npm uninstall 这个命令啊。。。我每次都直接删 node_modules

2016-10-09 14:51 GMT+08:00 Yiyu He <notifications@github.com>:

**Comment by fengmk2** [comment]
`rm -rf node_modules && cnpm i`
