### ISSUE TITLE
使用cnpm安装rollup相关依赖，构建项目报错

### ISSUE THREAD

**Issue by renaesop** [cnpm/cnpm#142]
可重现bug的[项目地址](https://github.com/renaesop/cnpm-rollup-bug.git)

执行`npm run build`

* 用npm安装依赖， 执行build不报错
* 用cnpm安装依赖，执行build报错

在OS X10.12和linux下用node6都测试过，都是这个情况

**Comment by dead-horse** [comment]
发一下报错信息

**Comment by renaesop** [comment]
报错如下
````
Error: Error transforming /tmp/cnpm-rollup-bug/src/hello.js with 'babel' plugin:
 It looks like your Babel configuration specifies a module transformer.
 Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead.
 See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at preflightCheck (/tmp/cnpm-rollup-bug/node_modules/.2.6.1@rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:43:102)
    at Object.transform$1 [as transform] (/tmp/cnpm-rollup-bug/node_modules/.2.6.1@rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:104:18)
    at /tmp/cnpm-rollup-bug/node_modules/.0.36.1@rollup/src/utils/transform.js:19:35
    at process._tickCallback (node.js:369:9)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
````

大概追查了一下，是`modify-babel-preset`对目录名的依赖的缘故，上面有pnmp的[相关issue](https://github.com/developit/modify-babel-preset/issues/5)，不过一直没有解决

**Comment by dead-horse** [comment]
@sorrycc modify-babel-preset 的问题有解决么？

**Comment by sorrycc** [comment]
https://github.com/developit/modify-babel-preset/issues/5
还没有。

**Comment by renaesop** [comment]
导致问题的代码[](https://github.com/developit/modify-babel-preset/blob/master/index.js#L71)

说到底还是symlink引起的，根源应该是在node的核心模块module,`Module._resolveFilename`。
#73

**Comment by renaesop** [comment]
developit/modify-babel-preset#16
提了个pr，在这个模块里特殊处理了symlink的情况

**Comment by fengmk2** [comment]
等待 modify-babel-preset 发布一个新版。

**Comment by fengmk2** [comment]
还需要去将 `babel-preset-es2015-rollup` 依赖的 modify-babel-preset 升级到 3

**Comment by fengmk2** [comment]
成功 build

![image](https://cloud.githubusercontent.com/assets/156269/19397616/16290fc0-927b-11e6-9d5d-cac586dae684.png)

**Comment by fengmk2** [comment]
https://github.com/rollup/babel-preset-es2015-rollup/pull/20
