### ISSUE TITLE
使用cnpm安装gulp-postcss后，单元测试报错

### ISSUE THREAD

**Issue by gucong3000** [cnpm/cnpm#145]
`gulp-postcss`中，clone代码后直接运行`cnpm i`, 然后运行`npm test`，就会报错。而直接使用npm安装依赖，则一切正常。原因不明。
见：https://github.com/postcss/gulp-postcss/issues/94

**Comment by fengmk2** [comment]
嗯，我看看。

**Comment by fengmk2** [comment]
就是你 pr 修复的问题 https://github.com/postcss/gulp-postcss/pull/96

**Comment by gucong3000** [comment]
在gulp-postcss那边修正了，但是我不确定cnpm这边是否有问题

**Comment by fengmk2** [comment]
模块正确安装了。

**Comment by fengmk2** [comment]
我使用 yarn 安装，也是一样报错的。

![image](https://cloud.githubusercontent.com/assets/156269/19335874/4782890e-9139-11e6-8157-46a519923e3b.png)
