### ISSUE TITLE
能否尽量确保依赖包被安装?

### ISSUE THREAD

**Issue by yyjdelete** [cnpm/cnpm#147]
```
node --version
v6.5.0

npm --version
3.10.3

cnpm --version
4.3.2
```
发现当某些时候由于网络原因, `cnpm install`时当某个包的依赖包下载失败时, 会正常报错
但当下次`cnpm install`, 不确定是`cnpm`还是`npminstall`的原因, 似乎是发现主包已被安装了, 然后就跳过了对其依赖包的解析下载(即使之前没有下载成功), 最终造成缺少依赖包, 只能删除node_modules重装, 能否对此情况进行一些优化处理

**Comment by dead-horse** [comment]
如果要完整分析整个目录依赖结构查到是否有缺少的文件太耗时间了，会导致正常情况下再次 install 过慢，考虑到 cnpm 现在的重新安装速度已经足够快了，所以建议还是删除重新安装比较好。

**Comment by fengmk2** [comment]
rm -rf node_modules && cnpm i

**Comment by fengmk2** [comment]
@dead-horse 是否完整安装完在加个标记文件 node_modules/.npminstall.done ，下次 npminstall 发现没有这个文件，就先删除 node_modules ？

**Comment by dead-horse** [comment]
有些情况下很难判断，例如 a 和 b 都依赖了 c，先安装 a 的时候，c 已经开始安装了，这时候开始安装 b，b 会认为 c 已经在安装过程中了，跳过 c 的安装。如果 c 失败了，b 无法感知到 c 安装失败了。
