### ISSUE TITLE
mac 下使用cnpm安装npm包，出现.0.2.1@Base64的引用

### ISSUE THREAD

**Issue by zuizuihao** [cnpm/cnpm#155]
使用cnpm在mac下安装npm包，理论上是直接在当前文件夹下面生成node_modules的各种npm包。实际测试中，发现会有各种引用，由于这个区别导致 使用npm和cnpm有差别，在开发中遇到困难。
<img width="101" alt="screenshot at nov 01 13-42-18" src="https://cloud.githubusercontent.com/assets/751194/19880566/58f960cc-a039-11e6-9bc0-aba47a384e10.png">
<img width="113" alt="screenshot at nov 01 13-42-40" src="https://cloud.githubusercontent.com/assets/751194/19880556/47bb3466-a039-11e6-8317-25a8c42cca39.png">

**Comment by alsotang** [comment]
cnpm用了 npminstall 这个库，所以目录结构有优化。如果想要 npm 自身的目录结构，可以直接使用 npm 客户端。
```
alias cnpm="npm --registry=https://registry.npm.taobao.org \
--cache=$HOME/.npm/.cache/cnpm \
--disturl=https://npm.taobao.org/mirrors/node \
--userconfig=$HOME/.cnpmrc"
```

具体是遇到什么麻烦了呢？

**Comment by fengmk2** [comment]
@alsotang 现在加一个参数就好了 `$ cnpm i --by=npm`

**Comment by fengmk2** [comment]
> 由于这个区别导致 使用npm和cnpm有差别，在开发中遇到困难

目录结构最终效果跟 npm@3 的是一样的，具体是什么差异呢？

**Comment by languanghao** [comment]
@fengmk2 终于找到原因了，原来是升级cnpm带来的错误，现在这种目录解构有个很大的问题，执行`cnpm update`的时候，`wanted`和`latested`显示的都是`linked`，这样就不知道到底有什么包升级了，而且如果手动改`package.json`文件里的一个包的版本号，这个时候是能检测出升级，但是`cnpm update`会出现错误`npm WARN update-linked ...... but we can't, as it's a symlink`

另外，根据上面说的，运行 `cnpm i --by=npm` 现在生成的目录解构是对的，不会有一堆的链接文件，但是我刚才安装`node-sass`，这个包会去github上下载编译好的文件，不知道是不是个bug。

**Comment by fengmk2** [comment]
请使用 [autod](https://npm.taobao.org/package/autod) 代替 npm update.
