### ISSUE TITLE
Error: unknown compression method

### ISSUE THREAD

**Issue by georgezouq** [cnpm/cnpm#160]
在执行
```
cnpm install 
```
的时候出现，如下错误，不仅仅是在一个项目中，好多项目中都无法安装

  <img width="563" alt="2016-11-14 2 45 52" src="https://cloud.githubusercontent.com/assets/5990860/20255639/32c070cc-aa79-11e6-84ad-f0244d12baea.png">

**Comment by georgezouq** [comment]
环境 OS X 10.11 
npm 3.10.9
cnpm 4.4.0
node v5.9.0

**Comment by dead-horse** [comment]
图可以截取完整一点么？

**Comment by dead-horse** [comment]
看上去是系统有点问题，不能解压

**Comment by fengmk2** [comment]
请将 node 升级到 6，然后 rm -rf node_modules 重试。

**Comment by georgezouq** [comment]
@dead-horse  @fengmk2  将nodejs升级7.10好使了, 谢谢
