### ISSUE TITLE
安装Ghost Blog的依赖时报错

### ISSUE THREAD

**Issue by lianer** [cnpm/cnpm#162]
Ghost Blog 的这些依赖会安装失败，最新版本的可以安装成功
nodemailer@0.7.1
gscan@0.0.15

![image](https://cloud.githubusercontent.com/assets/9332264/20333872/ba9ee5d2-abf0-11e6-963f-f39c5e93e218.png)

**Comment by fengmk2** [comment]
Ghost Blog 是那个库？

**Comment by lianer** [comment]
是一个nodejs博客框架，那时有几个模块的指定版本装不起来，但最新版都可以的，也许是网络问题，现在不能重现了。
