### ISSUE TITLE
cnpm安装反馈显示不全

### ISSUE THREAD

**Issue by sxcooler** [cnpm/cnpm#169]
比如deprecate xxx，前面不显示包名，导致用户不知道是哪个包报的信息，需要去猜，比较影响体验。
就像这样：
![image](https://cloud.githubusercontent.com/assets/3192045/20744956/b62e6df4-b719-11e6-948e-1c907ff6980d.png)

**Comment by fengmk2** [comment]
显示的，你的终端颜色跟灰色冲突了。

**Comment by sxcooler** [comment]
抱歉抱歉，是我的问题
