### ISSUE TITLE
Cnpm install 报错

### ISSUE THREAD

**Issue by superlbr** [cnpm/cnpm#172]
bug 出现在cnpm所引用的依赖包debug上
`/usr/lib/node_modules/cnpm/node_modules/debug/debug.js:126
  debug.color = selectColor(namespae);`
namespace，少了个c。。。

**Comment by superlbr** [comment]
![image](https://cloud.githubusercontent.com/assets/8142164/21174062/f7f43f14-c215-11e6-903b-723716937642.png)

**Comment by fengmk2** [comment]
debug 模块的问题 https://github.com/visionmedia/debug/pull/356

重新安装即可。
