### ISSUE TITLE
cnpm install -g XXX 后一直retry GET https://registry.npm.taobao.org/binary-mirror-config/latest

### ISSUE THREAD

**Issue by lingjieding** [cnpm/cnpm#174]
系统：centos6.6
node -v :  v6.9.1
npm -v : 3.10.8
cnpm -v : 4.4.2

然后 使用cnpm install -g  任意一个包时，出现一直 retry GET https://registry.npm.taobao.org/binary-mirror-config/latest 超时的现象:

[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 100ms, retry left 4, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npm.taobao.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 200ms, retry left 3, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npm.taobao.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":2,"closeSocketCount":2,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 300ms, retry left 2, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npm.taobao.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":3,"closeSocketCount":3,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 400ms, retry left 1, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npm.taobao.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":4,"closeSocketCount":4,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 100ms, retry left 4, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npm.taobao.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":6,"closeSocketCount":6,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 200ms, retry left 3, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npm.taobao.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":7,"closeSocketCount":7,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 300ms, retry left 2, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npm.taobao.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":8,"closeSocketCount":8,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 400ms, retry left 1, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npm.taobao.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":9,"closeSocketCount":9,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://r.cnpmjs.org/binary-mirror-config/latest after 100ms, retry left 4, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://r.cnpmjs.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":11,"closeSocketCount":11,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://r.cnpmjs.org/binary-mirror-config/latest after 200ms, retry left 3, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://r.cnpmjs.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":12,"closeSocketCount":12,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://r.cnpmjs.org/binary-mirror-config/latest after 300ms, retry left 2, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://r.cnpmjs.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":13,"closeSocketCount":13,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://r.cnpmjs.org/binary-mirror-config/latest after 400ms, retry left 1, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://r.cnpmjs.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":14,"closeSocketCount":14,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npmjs.org/binary-mirror-config/latest after 100ms, retry left 4, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npmjs.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":16,"closeSocketCount":16,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npmjs.org/binary-mirror-config/latest after 200ms, retry left 3, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npmjs.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":17,"closeSocketCount":17,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npmjs.org/binary-mirror-config/latest after 300ms, retry left 2, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npmjs.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":18,"closeSocketCount":18,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npmjs.org/binary-mirror-config/latest after 400ms, retry left 1, error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npmjs.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":19,"closeSocketCount":19,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
Get /binary-mirror-config/latest from https://registry.npm.taobao.org error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npmjs.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":20,"closeSocketCount":20,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
    at Timeout._onTimeout (/home/work/mySoftWare/node-v6.9.1-linux-x64/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:701:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
Downloading fis-parser-less to /home/work/mySoftWare/node-v6.9.1-linux-x64/lib/node_modules/fis-parser-less_tmp
Copying /home/work/mySoftWare/node-v6.9.1-linux-x64/lib/node_modules/fis-parser-less_tmp/.0.1.3@fis-parser-less to /home/work/mySoftWare/node-v6.9.1-linux-x64/lib/node_modules/fis-parser-less
Installing fis-parser-less's dependencies to /home/work/mySoftWare/node-v6.9.1-linux-x64/lib/node_modules/fis-parser-less/node_modules
less@1.7.5 installed at node_modules/.1.7.5@less
deprecate less@1.7.5 › request@2.40.0 › node-uuid@1.4.7 use uuid module instead

请问下这个是什么原因呢？

**Comment by fengmk2** [comment]
@lingjieding 你直接访问 https://registry.npm.taobao.org/binary-mirror-config/latest 能打开吗？

**Comment by lingjieding** [comment]
可以的，通过curl 可以拿到内容，就是慢了点

**Comment by fengmk2** [comment]
多慢？需要多长时间？

**Comment by lingjieding** [comment]
谢谢~
