### ISSUE TITLE
在cmd中查看node的模块'express'的版本，提示‘express’不是内部或外部命令 也不是可运行的程序，怎么解决？

### ISSUE THREAD

**Issue by ClarkCleson** [cnpm/cnpm#180]
通过npm install express -g安装了express模块后，通过express -v查看express的版本提示‘express’不是内部或外部命令 也不是可运行的程序。
已确认：C:\Program Files\nodejs\node_global\node_modules\express下的package.json文件中版本是"express@3.5.0"

**Comment by fengmk2** [comment]
你得看看 express 安装到哪里了，然后那个 bin 位置是否在环境变量 PATH 里面。

**Comment by inickel** [comment]
``` bash 
npm install -g express-generator
```
express和express的cli是区分开来的
