### ISSUE TITLE
cnpm 安装完依赖后不能正常使用的问题

### ISSUE THREAD

**Issue by chenglongzjg** [cnpm/cnpm#183]
先描述下情景吧：
从仓库里 clone 下项目后，使用 `cnpm i` 安装依赖，么有问题，依赖安装完毕，使用  `ng serve` 启动的时候，问题就来了，会报各式各样的错误让项目无法启动，这里我就贴一个例子： https://git.oschina.net/mumu-osc/NiceFish/issues/20

解决方案在贴的例子有。

所以问题是，这个问题你们有发现吗？我所在的群里经常有人会因为使用了 cnpm 安装依赖而出问题，导致很多不必要的麻烦。

各位大大，辛苦你们了  爱你们 😘

**Comment by qiyuan-wang** [comment]
因为cnpm使用的是npminstall安装依赖，所以文件的安装目录结构会跟npm安装有所区别。

**Comment by fengmk2** [comment]
如果你依赖的模块不支持 link 模式，可以使用 npm 模式来安装。

```bash
cnpm i --by=npm
```
