### ISSUE TITLE
使用registry的问题

### ISSUE THREAD

**Issue by inickel** [cnpm/cnpm#185]
在使用cnpm --registry=私有服务器地址之后
cnpm install 会优先从cnpm镜像读取，镜像上没有私有包的情况下导致读取404，不能正常安装。
是不是读取顺序上有调整过

**Comment by dead-horse** [comment]
不会的，cnpm 只会从指定的 regsitry 读取

**Comment by dead-horse** [comment]
你的场景我刚才测试过了是没有问题的，只会从指定的私有源读取

**Comment by inickel** [comment]
registryHost配置错了，没有设置成私有镜像的host。已经修复
