### ISSUE TITLE
怎样阻止cnpm通过在node_modules里面添加快捷方式的方式来安装包?

### ISSUE THREAD

**Issue by pronan** [cnpm/cnpm#191]
不知在什么时候起, 比如你安装bootstrap, npm会在node_modules里面放一个bootstrap的软连接, 真实安装地址是._bootstrap@3.3.7@bootstrap

初心是好的, 但是在我的工程中这种软连接不太方便. 有什么可以阻止这种行为吗

**Comment by XGHeaven** [comment]
`cnpm i --by=npm`

**Comment by fengmk2** [comment]
@XGHeaven Thanks.
