### ISSUE TITLE
使用cnpm安装next.js后报错找不到文件

### ISSUE THREAD

**Issue by thomasyxy** [cnpm/cnpm#194]
我本地clone了一个next.js项目，例如：https://github.com/now-examples/next-news

使用了cnpm install安装模块后运行npm run dev后next报错信息如下：

 ERROR  Failed to compile with 2 errors                                                                                                                                      19:20:57

These modules were not found:

* ../../../../._next@2.2.0@next/dist/lib/error.js in ./~/._next@2.2.0@next/dist/pages/_error.js?entry
* ../../../../._next@2.2.0@next/dist/server/document.js in ./~/._next@2.2.0@next/dist/pages/_document.js?entry

To install them, you can run: npm install --save ../../../../._next@2.2.0@next/dist/lib/error.js ../../../../._next@2.2.0@next/dist/server/document.js
Port 3000 is already in use.
Use `npm run dev -- -p <some other port>`.

npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/yixuan/.nvm/versions/node/v7.8.0/bin/node" "/Users/yixuan/.nvm/versions/node/v7.8.0/bin/npm" "run" "dev"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nextgram@ dev: `next`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nextgram@ dev script 'next'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nextgram package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     next
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nextgram
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nextgram
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yixuan/.npm/_logs/2017-04-26T11_20_57_534Z-debug.log

改用npm安装模块运行正常

node@7.8.0  npm@4.2.0
➔ cnpm -v
cnpm@4.5.0 (/Users/yixuan/.nvm/versions/node/v7.8.0/lib/node_modules/cnpm/parse_argv.js)
npm@3.10.10 (/Users/yixuan/.nvm/versions/node/v7.8.0/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@7.8.0 (/Users/yixuan/.nvm/versions/node/v7.8.0/bin/node)
npminstall@2.29.1 (/Users/yixuan/.nvm/versions/node/v7.8.0/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/Users/yixuan/.nvm/versions/node/v7.8.0
darwin x64 16.5.0
registry=https://registry.npm.taobao.org

**Comment by fengmk2** [comment]
@thomasyxy 重新安装 cnpm 即可。
