### ISSUE TITLE
Create angularjs project error: unknown option `--quiet'

### ISSUE THREAD

**Issue by srx4444** [cnpm/cnpm#195]
I set cnpm as angular-cli package manager:
`ng set --global packageManager=cnpm`

then create angularjs project by angular-cli:
`ng new myApp`

Some error occured:
`Installing packages for tooling via cnpm.

  error: unknown option --quiet'`

Seems like cnpm add argument '--quiet' to 'ng new' command which don't support.

How can I fix it?

> see also: [https://github.com/angular/angular-cli/issues/5650](https://github.com/angular/angular-cli/issues/5650)

**Comment by filipesilva** [comment]
This is a bug in Angular CLI, we will fix it there.

**Comment by dead-horse** [comment]
thanks @filipesilva
