### ISSUE TITLE
下载镜像源切换的一点疑问

### ISSUE THREAD

**Issue by onvno** [cnpm/cnpm#199]
更改镜像源的方式有以下这种
```
npm install package --registry=https://registry.npm.taobao.org
```
查看源码`npminstall`确实改了不少配置，不知道从下载效率上同`cnpm install package`差距如何。

因为尝试内网搭建镜像，想了解一点。

**Comment by XGHeaven** [comment]
如果我没记错，cnpm默认是使用npminstall安装的。

**Comment by alsotang** [comment]
https://github.com/cnpm/npminstall#benchmarks

**Comment by fengmk2** [comment]
只为一个字：快。
