### ISSUE TITLE
【重要】无法查看版本号，cnpm -v 无效了。

### ISSUE THREAD

**Issue by webees** [cnpm/cnpm#210]
我写了个批处理，每次点开都显示主要工具的版本号，但是最新版本cnpm -v无效！

**Comment by yubaoquan** [comment]
我这也是, -v 打印出来的信息好像变成 -h的信息了

**Comment by fengmk2** [comment]
呃。。。果然是，bug，我看看。

**Comment by fengmk2** [comment]
commander@2.11.0 is a broken change release https://github.com/tj/commander.js/issues/659

**Comment by fengmk2** [comment]
@webees @yubaoquan 安装最新版本即可。

**Comment by yubaoquan** [comment]
升级到5.1.1, 问题还在

**Comment by fengmk2** [comment]
我测试了是可以的，请确保是否正确安装了 cnpm 

![image](https://user-images.githubusercontent.com/156269/29033281-18ed035c-7bc7-11e7-9c5f-d88f43f1a97e.png)

**Comment by yubaoquan** [comment]
把cnpm整个删掉之后重装, 解决了.
