### ISSUE TITLE
使用cnpm安装后scss编译有缺失，npm没问题

### ISSUE THREAD

**Issue by ding-kai** [cnpm/cnpm#215]

**Comment by ding-kai** [comment]
具体哪个包导致的我也不好排查，cnpm跟npm不是只做了个镜像么？为什么install后会不一样？

**Comment by fengmk2** [comment]
能否给一个可重现的例子？

**Comment by ding-kai** [comment]
@fengmk2 [https://github.com/akveo/ng2-admin](url) 运行这个的时候发现的

**Comment by fengmk2** [comment]
不太懂 ng，你可以使用 cnpm i --by=npm 来解决。
