### ISSUE TITLE
安装模块失败, 报错

### ISSUE THREAD

**Issue by yubaoquan** [cnpm/cnpm#217]
### 版本
cnpm@5.1.1 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@5.3.0 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@8.1.2 (/usr/local/bin/node)
npminstall@3.1.1 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local
darwin x64 16.7.0
registry=http://registry.npm.taobao.org

### 错误描述
目测安装任何包都会报错, 以下是`cnpm i electron` 的日志

⠹ [0/1] Installing electron@~1.6.2[npminstall:get] retry GET electron after 100ms, retry left 4, error: RequestError: getaddrinfo ENOTFOUND electron electron:80 (req "error"), GET http://electron -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":2,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1,"freeSockets":{"registry.npm.taobao.org:80:":1},"sockets":{"electron:80:":1},"requests":{}})
headers: {}
⠸ [0/1] Installing electron@~1.6.2[npminstall:get] retry GET electron after 200ms, retry left 3, error: RequestError: getaddrinfo ENOTFOUND electron electron:80 (req "error"), GET http://electron -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":3,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1,"freeSockets":{"registry.npm.taobao.org:80:":1},"sockets":{"electron:80:":1},"requests":{}})
headers: {}
⠦ [0/1] Installing electron@~1.6.2[npminstall:get] retry GET electron after 300ms, retry left 2, error: RequestError: getaddrinfo ENOTFOUND electron electron:80 (req "error"), GET http://electron -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":2,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1,"freeSockets":{"registry.npm.taobao.org:80:":1},"sockets":{"electron:80:":1},"requests":{}})
headers: {}
⠏ [0/1] Installing electron@~1.6.2[npminstall:get] retry GET electron after 400ms, retry left 1, error: RequestError: getaddrinfo ENOTFOUND electron electron:80 (req "error"), GET http://electron -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":5,"createSocketErrorCount":0,"closeSocketCount":3,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1,"freeSockets":{"registry.npm.taobao.org:80:":1},"sockets":{"electron:80:":1},"requests":{}})
headers: {}
✖ Install fail! RequestError: getaddrinfo ENOTFOUND electron electron:80 (req "error"), GET http://electron -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":6,"createSocketErrorCount":0,"closeSocketCount":4,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1,"freeSockets":{"registry.npm.taobao.org:80:":1},"sockets":{"electron:80:":1},"requests":{}})
headers: {}
Error: getaddrinfo ENOTFOUND electron electron:80
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:91:26)
npminstall version: 3.1.1
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/baoquanyu/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=registry.npm.taobao.org

**Comment by fengmk2** [comment]
能够成功安装的

![image](https://user-images.githubusercontent.com/156269/29547873-6c005af8-872f-11e7-8991-58123bb56af4.png)

**Comment by fengmk2** [comment]
请看看你的 `~/.npmrc` 和 `~/.cnpmrc` 里面的 registry 配置是否正确。

**Comment by fengmk2** [comment]
> npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/baoquanyu/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=registry.npm.taobao.org

这个 ` --registry=registry.npm.taobao.org` 参数明显少了 `http://`

**Comment by yubaoquan** [comment]
是我的错 多谢!
