### ISSUE TITLE
当使用cnpm安装angular-cli，styles报错

### ISSUE THREAD

**Issue by eminoda** [cnpm/cnpm#218]
在angular-cli.json有一个引入外部资源css的配置`
````
"styles": [
        "../node_modules/font-awesome/css/font-awesome.min.css",
        "../node_modules/primeng/resources/primeng.min.css",
        "../node_modules/primeng/resources/themes/omega/theme.css",
        "styles.scss"
      ],
````
当我cnpm安装好angualr后，运行ng server，运行没报错。但是外部引入的资源文件未加载到index.html

我用npm install 重新安装后，问题解决。请问下是cnpm的问题吗

https://github.com/angular/angular-cli/issues/7606

**Comment by aeolusluck** [comment]
cnpm安装的node模块全部是以_开头,并且带有版本号,如果是在.angular-cli.json文件中添加css引用或者js引用的话需要添加实际的路径比如:
` "styles": [
        "styles.css",
        "../node_modules/_primeng@5.0.2@primeng/resources/primeng.min.css",
        "../node_modules/_font-awesome@4.7.0@font-awesome/css/font-awesome.min.css",
        "../node_modules/_primeng@5.0.2@primeng/resources/themes/darkness/theme.css"

      ],`
如果是在全局的style.css中引用样式则可以用下面的方式
`@import "~primeng/resources/primeng.min.css";
@import "~primeng/resources/themes/darkness/theme.css";
@import "~font-awesome/css/font-awesome.min.css";`

说实在的,这个坑我也排了好久,才发现用cnpm安装的node 模块依赖会自动以"_"开头,然后在建立个快捷方式,在.angular-cli.json中使用快捷方式引入无效,但是在style.css中用上面的写法就可以

**Comment by eminoda** [comment]
@aeolusluck 后头去试试，谢谢你啊，抽空码那么多字
