### ISSUE TITLE
cnpm何时支持package-lock.json

### ISSUE THREAD

**Issue by qianzhangsheng** [cnpm/cnpm#226]
npm现在安装以后会生成package-lock.json，cnpm何时会支持这个功能？

**Comment by chanjsq** [comment]
希望 `cnpm` 支持 `package-lock.json`，和 `npm` 保持行为一致

**Comment by blackLearning** [comment]
+1

**Comment by lianer** [comment]
+1

**Comment by sunchenguang** [comment]
是不是都不维护了。。

**Comment by Stupidism** [comment]
我现在直接用 `npm --registry=https://registry.npm.taobao.org i`

**Comment by popomore** [comment]
不打算支持，可以使用 @Stupidism 说的方式

**Comment by noscripter** [comment]
有一种实际的应用场景：CI，需要利用 package-lock.json 来锁定依赖版本，例如我依赖了 ant-design，不同版本的 ant-design 渲染出来的 snapshot 会不同，如果不用依赖锁定会导致快照对比失败测试用例失败。
