### ISSUE TITLE
请问有朋友碰到 cnpm install rxjs 无法安装的情况么

### ISSUE THREAD

**Issue by rthel** [cnpm/cnpm#227]
提示找不到 repository，需要用 npm 进行安装才行

**Comment by popomore** [comment]
贴一下具体日志

**Comment by rthel** [comment]
@popomore 抱歉我尝试一些方法，似乎没办法复现，这个问题我之前碰到过两次，都是全新的环境安装angular时候碰到的，提示 can't find repository，查看日志，发现下载地址指向了一个 GitHub 的 repo ，但是 repo 不存在，解决的方式是 `npm install rxjs` ，先关掉这个 issue 了
