### ISSUE TITLE
cnpm 现在不支持node >= 8.2.1 吗？

### ISSUE THREAD

**Issue by squirrelofmax** [cnpm/cnpm#229]
![qq20171104-0](https://user-images.githubusercontent.com/21050412/32403666-bce836b2-c10d-11e7-8eb5-4d30ce1ca6bf.png)

**Comment by fengmk2** [comment]
这是 got@5.0.0 不支持，不是 cnpm 不支持。

**Comment by squirrelofmax** [comment]
那为什么npm 可以正常安装got，而cnpm 会出现这种情况呢？

**Comment by squirrelofmax** [comment]
那为什么npm 可以直接安装got@5.7.1， 而cnpm 不能，两者的实现有什么区别吗？
