### ISSUE TITLE
安装 puppeteer 组件时，会安装一个超大的 headless chrome，非常慢，建议添加个镜像

### ISSUE THREAD

**Issue by qiu8310** [cnpm/cnpm#237]
安装 puppeteer 时，支持在环境变量中指定镜像地址 `PUPPETEER_DOWNLOAD_HOST`，参见 https://github.com/GoogleChrome/puppeteer/blob/v0.13.0/install.js

镜像资源参见文件 https://github.com/GoogleChrome/puppeteer/blob/v0.13.0/utils/ChromiumDownloader.js

注： `puppeteer` 组件是谷歌团队开发的用于做 headless chrome 测试用的一个 nodejs 组件

**Comment by fengmk2** [comment]
目前已经做了代理，只是代理速度不够快。

**Comment by fengmk2** [comment]
https://storage.googleapis.com/chromium-browser-snapshots/Mac/513435/chrome-mac.zip

**Comment by fengmk2** [comment]
可以从 http://registry.npmjs.com/puppeteer 里面读取到每个 `puppeteer.chromium_revision` 的版本号遍历下载。

**Comment by fengmk2** [comment]
https://cnpmjs.org/mirrors/chromium-browser-snapshots/ 好了。

**Comment by qiu8310** [comment]
刚试了下，安装不了！

puppeteer 的安装脚本写的比较简单，不支持重定向，你上面提供的地址有重定向

```bash
$ curl -I "https://cnpmjs.org/mirrors/chromium-browser-snapshots/Mac/515411/chrome-mac.zip"
HTTP/1.1 302 Found
Server: nginx/1.4.6 (Ubuntu)
Date: Tue, 26 Dec 2017 02:27:05 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 239
Connection: keep-alive
Vary: Accept-Encoding
Location: https://cnpmjs.oss-ap-southeast-1.aliyuncs.com/dist/chromium-browser-snapshots/Mac/515411/chrome-mac.zip
X-Response-Time: 3
Strict-Transport-Security: max-age=15768000
```

感觉这个应该去 puppeteer 上提个 issues 或者直接用你重定向后的域名 cnpmjs.oss-ap-southeast-1.aliyuncs.com
