### ISSUE TITLE
capture-stack-trace@1.0.1 这个包安装的时候出现 ShasumNotMatchError

### ISSUE THREAD

**Issue by immissile** [cnpm/cnpm#264]
Install fail! ShasumNotMatchError: real sha1:ed0a1edb87c05d4db1037c5f8f483d8a3b5f0825 not equal to remote:a6c0bbe1f38f3aa0b92238ecb6ff42c344d4135d (capture-stack-trace@1.0.1)

安装 capture-stack-trace@1.0.1 这个包安装的时候出现 ShasumNotMatchError 错误，用npm安装没问题，去capture-stack-trace的repo上看了下，1.0.1的release时间是11个小时之前，应该是昨天刚发布的版本

<img src="http://7xq4yv.com1.z0.glb.clouddn.com/WX20180901-105603.png">

会是什么问题？

**Comment by shengzihao** [comment]
我也遇到了同样的问题

**Comment by immissile** [comment]
暂时先加了个 preinstall 来处理了

scripts里加上：

`"preinstall": "cnpm install floatdrop/capture-stack-trace"`

直接用repo来安装

静等 @fengmk2 的根除秘方

**Comment by shengzihao** [comment]
先用npm了，除了慢点，其他倒是能用。
