### ISSUE TITLE
Install fail! Error: write after end (writeStream "error") (writeStream "error")

### ISSUE THREAD

**Issue by CharlesSong** [cnpm/cnpm#272]
操作系统：CentOS Linux release 7.3.1611 (Core)
node：8.11.2
npm：5.6.0
cnpm： 6.0.0                             

  ⠇ [60/70] Installing webpack-dev-server@^2.9.1(node:8728) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
[node-sass@4.11.0] download Error: write after end (writeStream "error") (writeStream "error"), GET https://cdn.npm.taobao.org/node-sass/-/node-sass-4.11.0.tgz 200 (connected: true, keepalive socket: false, agent status: {"createSocketCount":52,"createSocketErrorCount":0,"closeSocketCount":50,"errorSocketCount":0,"timeoutSocketCount":1,"requestCount":21,"freeSockets":{},"sockets":{"cdn.npm.taobao.org:443:::::::true::":2},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 1)
headers: {"server":"Tengine","content-type":"application/octet-stream","content-length":"389800","connection":"keep-alive","date":"Wed, 12 Dec 2018 12:41:57 GMT","x-oss-request-id":"5C110215BE0EBCEDB8D3E27F","accept-ranges":"bytes","etag":"\"7CE8C55082B17BF2C02A8E178DD3BB44\"","last-modified":"Thu, 15 Nov 2018 11:40:10 GMT","x-oss-object-type":"Normal","x-oss-hash-crc64ecma":"6325188998138411773","x-oss-storage-class":"Standard","cache-control":"max-age=0, s-maxage=86400","content-md5":"fOjFUIKxe/LAKo4XjdO7RA==","x-oss-server-time":"3","via":"cache6.l2et2-1[0,304-0,H], cache1.l2et2-1[3,0], cache12.cn1306[0,200-0,H], cache18.cn1306[1,0]","age":"83010","ali-swift-global-savetime":"1542282075","x-cache":"HIT TCP_MEM_HIT dirn:12:212459181","x-swift-savetime":"Wed, 12 Dec 2018 15:50:04 GMT","x-swift-cachetime":"75113","timing-allow-origin":"*","eagleid":"907b1fa615447015275794322e"}, fail count: 3
✖ Install fail! Error: write after end (writeStream "error") (writeStream "error"), GET https://cdn.npm.taobao.org/node-sass/-/node-sass-4.11.0.tgz 200 (connected: true, keepalive socket: false, agent status: {"createSocketCount":52,"createSocketErrorCount":0,"closeSocketCount":50,"errorSocketCount":0,"timeoutSocketCount":1,"requestCount":21,"freeSockets":{},"sockets":{"cdn.npm.taobao.org:443:::::::true::":2},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 1)
headers: {"server":"Tengine","content-type":"application/octet-stream","content-length":"389800","connection":"keep-alive","date":"Wed, 12 Dec 2018 12:41:57 GMT","x-oss-request-id":"5C110215BE0EBCEDB8D3E27F","accept-ranges":"bytes","etag":"\"7CE8C55082B17BF2C02A8E178DD3BB44\"","last-modified":"Thu, 15 Nov 2018 11:40:10 GMT","x-oss-object-type":"Normal","x-oss-hash-crc64ecma":"6325188998138411773","x-oss-storage-class":"Standard","cache-control":"max-age=0, s-maxage=86400","content-md5":"fOjFUIKxe/LAKo4XjdO7RA==","x-oss-server-time":"3","via":"cache6.l2et2-1[0,304-0,H], cache1.l2et2-1[3,0], cache12.cn1306[0,200-0,H], cache18.cn1306[1,0]","age":"83010","ali-swift-global-savetime":"1542282075","x-cache":"HIT TCP_MEM_HIT dirn:12:212459181","x-swift-savetime":"Wed, 12 Dec 2018 15:50:04 GMT","x-swift-cachetime":"75113","timing-allow-origin":"*","eagleid":"907b1fa615447015275794322e"}
Error: write after end (writeStream "error") (writeStream "error"), GET https://cdn.npm.taobao.org/node-sass/-/node-sass-4.11.0.tgz 200 (connected: true, keepalive socket: false, agent status: {"createSocketCount":52,"createSocketErrorCount":0,"closeSocketCount":50,"errorSocketCount":0,"timeoutSocketCount":1,"requestCount":21,"freeSockets":{},"sockets":{"cdn.npm.taobao.org:443:::::::true::":2},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 1)
headers: {"server":"Tengine","content-type":"application/octet-stream","content-length":"389800","connection":"keep-alive","date":"Wed, 12 Dec 2018 12:41:57 GMT","x-oss-request-id":"5C110215BE0EBCEDB8D3E27F","accept-ranges":"bytes","etag":"\"7CE8C55082B17BF2C02A8E178DD3BB44\"","last-modified":"Thu, 15 Nov 2018 11:40:10 GMT","x-oss-object-type":"Normal","x-oss-hash-crc64ecma":"6325188998138411773","x-oss-storage-class":"Standard","cache-control":"max-age=0, s-maxage=86400","content-md5":"fOjFUIKxe/LAKo4XjdO7RA==","x-oss-server-time":"3","via":"cache6.l2et2-1[0,304-0,H], cache1.l2et2-1[3,0], cache12.cn1306[0,200-0,H], cache18.cn1306[1,0]","age":"83010","ali-swift-global-savetime":"1542282075","x-cache":"HIT TCP_MEM_HIT dirn:12:212459181","x-swift-savetime":"Wed, 12 Dec 2018 15:50:04 GMT","x-swift-cachetime":"75113","timing-allow-origin":"*","eagleid":"907b1fa615447015275794322e"}
    at writeAfterEnd (_stream_writable.js:236:12)
    at WriteStream.Writable.write (_stream_writable.js:287:5)
    at IncomingMessage.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at IncomingMessage.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npminstall version: 3.16.0
npminstall args: /usr/local/bin/node /opt/node-v10.13.0-linux-x64/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/root/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org

**Comment by alsotang** [comment]
https://gist.github.com/alsotang/f654af8b1fff220e63fcb44846423e6d
