### ISSUE TITLE
同步同是阿里旗下的库babel-plugin-dva-hmr失败

### ISSUE THREAD

**Issue by vipcxj** [cnpm/cnpm#286]
babel-plugin-dva-hmr在昨天更新到了0.4.2，解决了一个非常非常严重的bug，然后cnpm查不到0.4.2的版本，于是我用`cnpm sync babel-plugin-dva-hmr`来手动同步，根据打印的日志，淘宝服务器获取到的最新版本是0.4.1，而不是0.4.2，故未执行更新操作，估计这也是更新这个包失败的原因。cnpm的服务器获取包最新版本的api可能存在严重问题。

**Comment by vipcxj** [comment]
另外，npmjs官网上搜索框里提升最新版本是0.4.1，但精确搜索到这个包后，显示的最新版本确实是0.4.2。webstorm里有自动获取npm包最新的版本功能，这个功能确确实实获取到了0.4.2这个最新版的版本号。所以我认为npm可能存在多种方式获取一个包的最新版本，其中一个方式存在问题，而不幸的是，cnpm使用了这种有问题的api

**Comment by vipcxj** [comment]
通过`https://npm.taobao.org/sync/babel-plugin-dva-hmr`网站同步的方式终于同步成功了，虽然搞定了，但感觉这应该是个bug~

**Comment by fengmk2** [comment]
同步不一定可以实时成功，如果发现了有版本遗漏，请使用 sync 功能同步缺失的版本。

**Comment by vipcxj** [comment]
@fengmk2 已经说了，使用cnpm的sync命令并没有什么卵用，最后是使用`https://npm.taobao.org/sync/babel-plugin-dva-hmr`网站同步才成功

**Comment by fengmk2** [comment]
babel-plugin-dva-hmr@0.4.2 的数据同步出现丢失，昨天已经解决了。
