### ISSUE TITLE
官网挂了 https://npm.taobao.org/

### ISSUE THREAD

**Issue by xiongmeiqiang123** [cnpm/cnpm#288]
![image](https://user-images.githubusercontent.com/6100541/58299001-28c3ae00-7e10-11e9-915c-a126f5d7a2ff.png)

**Comment by shady-xia** [comment]
服务器挂了，npm又用不了 现在焦急地等待

**Comment by mystylemylife** [comment]
同求，现在无法cnpm install

**Comment by huguobo** [comment]
https://registry.npm.taobao.org/   源也经常性500

**Comment by mystylemylife** [comment]
> https://registry.npm.taobao.org/ 源也经常性500

是的

**Comment by fengmk2** [comment]
fixed

**Comment by wanming** [comment]
现在又挂了
