### ISSUE TITLE
同步不到新包

### ISSUE THREAD

**Issue by seeliu** [cnpm/cnpm#291]
![image](https://user-images.githubusercontent.com/2050038/59489151-f871ab80-8eb3-11e9-88d4-85ca54165d93.png)

![image](https://user-images.githubusercontent.com/2050038/59489211-1d661e80-8eb4-11e9-97c3-344faa51391f.png)

这个包一直没有同步过来

**Comment by alsotang** [comment]
https://npm.taobao.org/package/scratch-paint

**Comment by seeliu** [comment]
https://npm.taobao.org/package/scratch-paint
https://npm.taobao.org/package/scratch-paint
https://npm.taobao.org/package/scratch-paint
https://npm.taobao.org/package/scratch-paint
https://npm.taobao.org/package/scratch-paint

**Comment by seeliu** [comment]
http://npm.taobao.org/package/scratch-audio  
http://npm.taobao.org/package/scratch-blocks
http://npm.taobao.org/package/scratch-l10n
http://npm.taobao.org/package/scratch-paint
http://npm.taobao.org/package/scratch-render
http://npm.taobao.org/package/scratch-storage
http://npm.taobao.org/package/scratch-svg-renderer
http://npm.taobao.org/package/scratch-vm
这些包同样的问题

**Comment by fengmk2** [comment]
@alsotang 0.2.0-prerelease.20190524133325 版本号超过了数据库字段长度。。。

**Comment by fengmk2** [comment]
需要执行下面的 sql 变更

```sql
ALTER TABLE `module` 
	MODIFY COLUMN `version` varchar(70) CHARACTER SET utf8 NOT NULL COMMENT 'module version';
```

```sql
ALTER TABLE `tag` 
	MODIFY COLUMN `version` varchar(70) CHARACTER SET utf8 NOT NULL COMMENT 'module version';
```

**Comment by fengmk2** [comment]
https://cnpmjs.org/package/scratch-paint 已经OK，今晚凌晨对 npm.taobao.org 做数据库变更。

**Comment by fengmk2** [comment]
```sql
【执行SQL：(1)】

ALTER TABLE `module` 
	MODIFY COLUMN `version` varchar(70) CHARACTER SET utf8 NOT NULL COMMENT 'module version'

执行成功，耗时：[784294ms.]
```

**Comment by fengmk2** [comment]
@alsotang @seeliu all fixed

**Comment by alsotang** [comment]
@fengmk2 
我研究一下mysql更改字段的锁表问题，需要很谨慎。
我这边mysql的版本是 5.7，taobao npm 这边是多少版本？

**Comment by alsotang** [comment]
我印象中不同版本的锁表行为不一样的。

**Comment by alsotang** [comment]
我这里 mysql 5.7 ，alter table的时候，tnpm publish 和 tnpm install 都照常进行。都不锁表。

数据库情况如下：
`select count(*) from module` => `共 1245779 行, 查询花费 0.5285 秒`
`select count(*) from tag` => `(共 100503 行, 查询花费 0.0444 秒。)`
