### ISSUE TITLE
怎么获取统计私有包下载数？

### ISSUE THREAD

**Issue by blankPen** [cnpm/cnpm#294]
如题，不知道cnpm是否提供了api能够获取到特定包在指定时间段的下载量。
期望是有一个和 https://github.com/npm/download-counts 类似的接口

**Comment by alsotang** [comment]
https://github.com/cnpm/cnpmjs.org/blob/45408450465281d4298108f090a5807d141b7c6d/routes/registry.js#L107

**Comment by hua1995116** [comment]
找了一圈没找到可视化，自己写了一个。 https://cnpm-stat.com/?packages=vue&startTime=2020-05-01&endTime=2020-10-01
