### ISSUE TITLE
安装 weui.js 版本匹配出错

### ISSUE THREAD

**Issue by wisetc** [cnpm/cnpm#297]
cnpm 版本5.1.1

```
$ cnpm -v
cnpm@5.1.1 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@5.4.2 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@8.9.3 (/usr/local/bin/node)
npminstall@3.1.4 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local
darwin x64 17.5.0
registry=http://registry.npm.taobao.org
```

假设匹配规则为，`"weui.js": "^1.1.3",` 但是实际安装的 weui.js 版本为 `1.2.1`，

```json
{
  "name": "weui.js",
  "version": "1.2.1"
}
```

期望匹配到 `1.1.x`，而不是 `1.2.x`

**Comment by wisetc** [comment]
依据 <https://docs.npmjs.com/about-semantic-versioning>
![image](https://user-images.githubusercontent.com/9448115/64307904-17bb3900-cfca-11e9-9621-0946ec7570a7.png)

**Comment by wisetc** [comment]
weui.js 1.1.3 正确匹配规则为 `"weui.js": "~1.1.3"`，用错。

**Comment by alsotang** [comment]
直接写 `1.1.x` 简单

**Comment by wisetc** [comment]
是的，谢谢。因为要和 weui 版本匹配，所以现在 weui weui.js 都锁写 1.1.3。thank you.




在2019年09月05日 11:10，alsotang 写道：

直接写 1.1.x 简单
