### ISSUE TITLE
support $INIT_CWD when install

### ISSUE THREAD

**Issue by afc163** [cnpm/cnpm#317]
### Reproduce steps

```
mkdir test
cd test
git init
cnpm i husky@4.0.3 --save-dev
```

Error message:

```
husky > Setting up git hooks
Cannot destructure property `name` of 'undefined' or 'null'.
husky > Failed to install
```

<img width="842" alt="image" src="https://user-images.githubusercontent.com/507615/72044111-e216bb80-32ed-11ea-97b4-0bed2799a9d5.png">

### 原因

cnpm 和 tnpm 没有像 npm 和 yarn 一样添加 `$INIT_CWD` 环境变量：https://github.com/typicode/husky/blob/0ffe7853853dd7667ddc24a78469b92b5312aeb2/src/installer/bin.ts#L40

相关 issue：https://github.com/yarnpkg/yarn/issues/5698

**Comment by afc163** [comment]
same issue: https://github.com/typicode/husky/issues/640

**Comment by fengmk2** [comment]
好的，尽快修复。

**Comment by fengmk2** [comment]
https://docs.npmjs.com/cli/run-script

> Scripts are run from the root of the module, regardless of what your current working directory is when you call npm run. If you want your script to use different behavior based on what subdirectory you’re in, you can use the **INIT_CWD** environment variable, which holds the full path you were in when you ran npm run.

**Comment by fengmk2** [comment]
https://github.com/npm/npm/pull/12356/files#diff-8c44327c5a50975dee6ded9e9789e96eR81
