### ISSUE TITLE
cnpm 网页同步无效

### ISSUE THREAD

**Issue by xuya227939** [cnpm/cnpm#327]
网页同步提示成功，最新版1.9.11

![image](https://user-images.githubusercontent.com/16217324/88355870-9d89d380-cd98-11ea-86be-b02e07f39405.png)

但是，查看包名最新版本还是停留在1.9.6

![image](https://user-images.githubusercontent.com/16217324/88355893-b4c8c100-cd98-11ea-8fbe-387427b203e0.png)

请问如何解决？

包名：corki-ui

**Comment by uwang** [comment]
同样的问题，最近阿里系的镜像源全面崩溃啊

**Comment by fengmk2** [comment]
![image](https://user-images.githubusercontent.com/156269/126029651-b26c55af-18f2-4345-a88b-5423ad4f2500.png)

后续可以使用 cnpm sync pkg-name 来重试。
