### ISSUE TITLE
4 天前的 npm 包的最新版本没有同步过来

### ISSUE THREAD

**Issue by zhangwinning** [cnpm/cnpm#328]
这个最新版本 是 0.2.0 https://www.npmjs.com/package/fastify-error
但是这个还是 0.1.0 https://developer.aliyun.com/mirror/npm/package/fastify-error

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/89368109-4e835d00-d70d-11ea-8b76-4b79a84bd609.png)
