### ISSUE TITLE
use cnpm install project cause idea can not load the code hint for the dependency such as element-ui

### ISSUE THREAD

**Issue by QiuSoft** [cnpm/cnpm#330]

**Comment by QiuSoft** [comment]
but use npm to install project is ok.

**Comment by atian25** [comment]
IDEA does not work well with a symlink.

try to install https://www.npmjs.com/package/webstorm-disable-index

then config this to ignore from file list

![image](https://user-images.githubusercontent.com/227713/92539927-9ac63d80-f275-11ea-835d-eefb5aa22104.png)
