### ISSUE TITLE
github默认分支由master改成main导致无法安装包的问题

### ISSUE THREAD

**Issue by wmz46** [cnpm/cnpm#334]
背景：
1.现在在github上新建仓库默认分支名是main，不再是master。
2.自己写的包没有发布到npm官网。

所以使用github仓库直接安装包的方式，命令如下：
cnpm install <github用户名>/<github仓库名>

注：cnpm版本：6.1.1

由于没有master分支，所以安装会失败，只能自己手动新建一个master分支作为默认分支才能正常，有其他更加优雅的解决方案吗？

**Comment by atian25** [comment]
cnpm install <github用户名>/<github仓库名>#<分支名>
