### ISSUE TITLE
Install fail! ResponseError: read ECONNRESET, GET https://github.com/component/global/archive/v2.0.1.tar.gz 

### ISSUE THREAD

**Issue by asyncTime** [cnpm/cnpm#344]
Install fail! ResponseError: read ECONNRESET, GET https://github.com/component/global/archive/v2.0.1.tar.gz

**Comment by fengmk2** [comment]
这是直接去下载远程模块文件了，不是 npm 的文件了，无法被镜像的。你只能自行解决网络问题。
