### ISSUE TITLE
cnpm No matching version found for fastify-cron@1.1.2 but the package is in npm

### ISSUE THREAD

**Issue by radiorz** [cnpm/cnpm#347]
cnpm No matching version found for fastify-cron@1.1.2 but the package is in npm .why ?

**Comment by killagu** [comment]
![image](https://user-images.githubusercontent.com/6897780/127439627-fa8ee0b0-cdc1-4a6d-aff0-4faafd3d0de2.png)

If version or package is missed from cnpm, please use the `sync`.( And I have synced for you)
