### ISSUE TITLE
Heard of  this is better than pnpm, any benchmarks ?

### ISSUE THREAD

**Issue by yufengwang** [cnpm/cnpm#354]
I'm curious about the benchmark data, such as 
https://pnpm.io/benchmarks.
It would be great to show some statistics, thank you

**Comment by fengmk2** [comment]
cc @atian25

**Comment by atian25** [comment]
it's still under development and not open source yet, please stay tuned for it to be open source

see https://dev.to/atian25/in-depth-of-tnpm-rapid-mode-how-could-we-fast-10s-than-pnpm-3bpp for more detail.
