### ISSUE TITLE
case sensiitveness of package name

### ISSUE THREAD

**Issue by DustinCheng** [cnpm/cnpm#357]
cnpm handles package name in case insensitive way while npm is case sensitve.
i.e.
`cnpm info filelist` gets same result as `cnpm info FileList` but
`npm info filelist` is different from `npm info FileList`

**Comment by DustinCheng** [comment]
cnpm@7.1.0

**Comment by Baoyx007** [comment]
+1, 导致私服同步包出错 @fengmk2 

![Uploading image.png…]()

https://github.com/mde/filelist/issues/12

**Comment by otakustay** [comment]
我详细描述下情况：

非常初期的NPM是没有包名限制的，这导致有一些包名包含大写等非规范的字段，`FileList`（最后一次版本是在7年前）就是一个典型。

首先，官方的镜像上有[filelist](https://registry.npmjs.com/filelist)和[FileList](https://registry.npmjs.com/FileList)两个包，这两个包是不同的东西，前者是一个非常常用的包，后者用得不多。

而npmmirror的实现看上去是大小写不敏感的，很巧的是，它同步的**版本**（包括`time`和`versions`）是`filelist`（常用的那个）的，但其中的`name`（还有`readme`但这个不重要）字段又是`FileList`（有大小写的）。

这导致，一些工具，比如流行的verdaccio，在拿到npmmirror的响应之后，会重新再校验一下`name`字段是否和请求的相同，就会因为大小写不同而报错：

![image](https://user-images.githubusercontent.com/639549/152755529-8d8096f3-0ad6-4400-9ddf-1205567f2661.png)

考虑到`FileList`本身用得非常少，我的建议是在npmmirror无法低成本地修改为大小写敏感的前提下，直接把https://registry.npmmirror.com/filelist 中的`name`和`_id`字段改成`filelist`（全小写），最好再同步修改一下`readme`字段，大致就能满足要求了

**Comment by fengmk2** [comment]
@otakustay 非常感谢提供这么具体的信息。已经按你的建议进行修复 https://registry.npmmirror.com/filelist
