### ISSUE TITLE
建议增加 Playwright 的浏览器镜像

### ISSUE THREAD

**Issue by FrancisKong** [cnpm/cnpm#359]
[Playwright](https://playwright.dev) 是一个 e2e 测试框架，执行 `npx playwright install` 时会从微软的 CDN 下载 Headless 浏览器，下载速度非常慢，希望能够增加镜像，提升下载浏览器速度。

Playwright 支持执行 install 命令时传入 `PLAYWRIGHT_DOWNLOAD_HOST` 变量：[Download from artifact repository - Playwright](https://playwright.dev/docs/browsers#download-from-artifact-repository)，可以通过这种方式设置下载的镜像。

微软的 CDN 地址示例：https://playwright.azureedge.net/builds/chromium/938553/chromium-win64.zip

**Comment by fengmk2** [comment]
@FrancisKong 可以参考 https://github.com/cnpm/cnpmcore/pull/154 来提交一个 pr，估计今晚就能合并发布。

**Comment by fengmk2** [comment]
https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/utils/registry.ts 看起来比较复杂，如果你觉得实现比较难，我们会找时间来实现一下。

**Comment by FrancisKong** [comment]
> https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/utils/registry.ts 看起来比较复杂，如果你觉得实现比较难，我们会找时间来实现一下。

嗯，我先参照这个 https://github.com/cnpm/cnpmcore/blob/main/app/common/adapter/binary/PuppeteerBinary.ts 实现试试

**Comment by fengmk2** [comment]
@FrancisKong 给力，就交给你了。

**Comment by mnixry** [comment]
我在 https://github.com/cnpm/cnpmcore/pull/232 尝试实现了一下Playwright的镜像，欢迎各位大佬前来review
