### ISSUE TITLE
electron打包下载依赖404问题

### ISSUE THREAD

**Issue by Clownzoo** [cnpm/cnpm#360]
<img width="709" alt="image" src="https://user-images.githubusercontent.com/17718043/153328087-08d16c1d-e6bc-4f92-8f50-634e01f71caf.png">
实际地址：
https://npm.taobao.org/mirrors/electron/v13.6.6/electron-v13.6.6-win32-x64.zip

**Comment by fengmk2** [comment]
请提供一下复现方式

**Comment by alienzhangyw** [comment]
使用electron-builder打包，.yarnrc里面electron_mirror不管设置https://npmmirror.com/mirrors/electron/还是原先的https://npm.taobao.org/mirrors/electron/都会报404

**Comment by fengmk2** [comment]
@alienzhangyw 如何复现？提供一个最小可复现的代码库或者命令行？

**Comment by alienzhangyw** [comment]
https://github.com/electron-react-boilerplate/electron-react-boilerplate
```
yarn config set electron_mirror 'https://npmmirror.com/mirrors/electron/'
yarn
yarn package
```
![image](https://user-images.githubusercontent.com/58874541/154258191-ab2f547f-dd05-47c1-b682-17825875846b.png)

**Comment by fengmk2** [comment]
@alienzhangyw 你修改一下设置即可

```bash
yarn config set electron_mirror 'https://npmmirror.com/mirrors/electron/v'
```
