### ISSUE TITLE
‼️ ‼️ ‼️ ‼️ 「重要通知」原淘宝 npm 域名即将停止解析 ‼️ ‼️ ‼️ ‼️ 

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpm#361]
npm.taobao.org 和 registry.npm.taobao.org 将在 2022.06.30 号正式下线和停止 DNS 解析。

新域名切换规则：

- npm.taobao.org => npmmirror.com
- registry.npm.taobao.org => registry.npmmirror.com

因此，有强依赖老域名的各位开发者请尽快更新到新域名，可能受到的影响和处理方式：

- 企业用户需要联系 网管/IT/SRE 更新防火墙白名单。
- 存量应用的 lock 文件，开发者需要自行执行 sed 等指令去替换或重新生成。
- 本地 npmrc 里面的 registry 地址（如果有，则）需要开发者自行更新。
- 开发者自己的 CL 工具 或 平台应用 里面写死的地址，需开发者自己更新并部署。
- cnpm cli / nrm 等工具，对应的社区同学已经提 PR 更新，大家重新安装最新版本即可。（如发现遗漏麻烦知会下我们）

详细说明请移步 https://zhuanlan.zhihu.com/p/465424728

**Comment by fengmk2** [comment]
一个历史的 CDN 写死路径升级：

https://cdn.npm.taobao.org/dist/node/
=>
https://cdn.npmmirror.com/binaries/node/

**Comment by fengmk2** [comment]
今天会进行 301 强制永久性跳转：

- https://registry.nlark.com == 301 => https://registry.npmmirror.com

**Comment by frontend-winter** [comment]
done

**Comment by fengmk2** [comment]
npm.taobao.org 域名停止解析生效。
