### ISSUE TITLE
npm镜像https://npmmirror.com/mirrors/npm/ 目录为空

### ISSUE THREAD

**Issue by Gardent** [cnpm/cnpm#364]
最近在使用nvm-windows安装node发现，node安装成功，对应的npm安装失败，发现https://npmmirror.com/mirrors/npm/ 目录下是空的，以前是有数据。现在是更换了地址，还是无法用这种方式了？

**Comment by fengmk2** [comment]
@Gardent 我今晚会修复。

**Comment by fengmk2** [comment]
https://github.com/coreybutler/nvm-windows/blob/f792f4ec5e3b4c5abe541002118e7c1bba1844ac/README.md#upgrading-nvm-windows

**Comment by fengmk2** [comment]
@Gardent 可以了 https://npmmirror.com/mirrors/npm/v6.14.12.zip
