### ISSUE TITLE
github.com.cnpmjs.org无法访问

### ISSUE THREAD

**Issue by Fgaoxing** [cnpm/cnpm#366]
github.com.cnpmjs.org无法访问，请尽快修复

**Comment by atian25** [comment]
这个域名被 github 和 chrome 认定为钓鱼域名，同时回归 cnpm 的本心，我们提供的是包镜像服务，而不是 GitHub 代理服务。这超出了我们的职责。因此我们已经停止了该代理行为。

**Comment by Spz2022** [comment]
no....
