### ISSUE TITLE
sentry-cli 二进制文件 404

### ISSUE THREAD

**Issue by shaodahong** [cnpm/cnpm#368]
https://cdn.npmmirror.com/binaries/sentry-cli/1.73.2/sentry-cli-Darwin-universal

![image](https://user-images.githubusercontent.com/14831261/156962878-eaa65830-3616-45d6-a9e9-7350c4114902.png)

**Comment by LiuJinYang9527** [comment]
+1

**Comment by LiuJinYang9527** [comment]
![image](https://user-images.githubusercontent.com/25171074/156965743-7e72ef16-2804-4dc9-b2e3-fd06557c8c47.png)

我看cnpm官网上有1.73.2的版本，但是对应的CDN文件 404

**Comment by frankcloudy** [comment]
+1 目前遇到一样的问题

**Comment by fengmk2** [comment]
https://npmmirror.com/mirrors/sentry-cli/1.73.2/sentry-cli-Darwin-universal

https://npmmirror.com/mirrors/sentry-cli/ 我看都已经同步了。
