### ISSUE TITLE
包丢失

### ISSUE THREAD

**Issue by langcs** [cnpm/cnpm#369]
![image](https://user-images.githubusercontent.com/22113740/160046532-f38293f8-0030-429e-a2a9-a6d7993ec82c.png)
![image](https://user-images.githubusercontent.com/22113740/160046607-dea657d3-918d-4a47-88f9-92ce94e61c38.png)

**Comment by langcs** [comment]
npm上还有一个大写10年前的JSV包
cnpm上只有小写的6年前的jsv包

**Comment by langcs** [comment]
![image](https://user-images.githubusercontent.com/22113740/160046852-9cc19350-904c-4f6e-9ffe-2c7083345aba.png)

**Comment by tian-jeff** [comment]
same question.

**Comment by langcs** [comment]
> 

解决了吗

**Comment by langcs** [comment]
> same question.

解决了吗

**Comment by tian-jeff** [comment]
这个解决不了的，需要他们支持的。
我们的解决办法是切换registry，开启本地缓存
npm config set registry https://registry.npmjs.org

**Comment by langcs** [comment]
> 这个解决不了的，需要他们支持的。 我们的解决办法是切换registry，开启本地缓存 npm config set registry https://registry.npmjs.org

很奇怪 我们昨晚可以 今早上不行了

**Comment by tian-jeff** [comment]
可能是切换的原因，老的淘宝镜像切换到这个上边？猜的，我们也是之前可以今天突然不行了

**Comment by fengmk2** [comment]
cnpmcore 存在一个同步大写的漏洞，我已经重新同步了 https://npmmirror.com/sync/jsv?spm=a2c6h.24755359.0.0.333ca91bg35PLp#logid=623d57c66174f169bbf06a49

修复代码在 https://github.com/cnpm/cnpmcore/pull/192

**Comment by langcs** [comment]
> cnpmcore 存在一个同步大写的漏洞，我已经重新同步了 https://npmmirror.com/sync/jsv?spm=a2c6h.24755359.0.0.333ca91bg35PLp#logid=623d57c66174f169bbf06a49
> 
> 修复代码在 [cnpm/cnpmcore#192](https://github.com/cnpm/cnpmcore/pull/192)

哥 16小时前你改了匹配规则 cnpm上面就没大写的JSV包了 小写的这个同步是成功了 但我们项目中用到的是大写的JSV包

**Comment by tian-jeff** [comment]
可能没有仔细看问题描述，这是两个问题

**Comment by langcs** [comment]
> ![image](https://user-images.githubusercontent.com/22113740/160046852-9cc19350-904c-4f6e-9ffe-2c7083345aba.png)

> 可能没有仔细看问题描述，这是两个问题

对的 主要是这个安装失败问题 为什么找不到 排查结果就是npm上有 cnpm上没有 包名大小写区分

**Comment by langcs** [comment]
https://npmmirror.com/package/JSV 这个搜索出来的结果 不是想要的那个包

**Comment by tian-jeff** [comment]
你可以reopen这个问题吗？

**Comment by Bluesgavin** [comment]
同JSV求解决😢

**Comment by imba97** [comment]
同样遇到了这个问题
```
> cnpm i
✖ Install fail! Error: [jsonlint@1.6.3 › JSV@^4.0.x] Can't find package JSV@^4.0.x
Error: [jsonlint@1.6.3 › JSV@^4.0.x] Can't find package JSV@^4.0.x
    at resolve (C:\Users\syd-06\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:80:11)
    at async module.exports (C:\Users\syd-06\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:22:19)
    at async module.exports (C:\Users\syd-06\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\index.js:21:10)
    at async _install (C:\Users\syd-06\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:124:16)
    at async install (C:\Users\syd-06\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:26:12)
    at async mapper (C:\Users\syd-06\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:270:9)
```

**Comment by markixy** [comment]
同样遇到了这个问题，尝试了一下，可行。（临时方案！）
由于我用的是 `yarn`，往 `yarn.lock` 添加如下配置后，`yarn install` 成功。
```
JSV@^4.0.x:`
  name JSV
  version "4.0.0"
  resolved "https://registry.npmjs.org/JSV/-/JSV-4.0.0.tgz"
```

同理，如果用的是 `npm`，讲道理往 `package-lock.json` 添加配置也应该是可以的。
```
"JSV": {
    "version": "4.0.0",
    "resolved": "https://registry.npmjs.org/JSV/-/JSV-4.0.0.tgz"
},
```

**Comment by fengmk2** [comment]
https://npmmirror.com/package/JSV

大写的包已经修复了。目前通过黑名单实现。

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmjs.org/issues/1726#issuecomment-1079550405
