### ISSUE TITLE
npm install -g cnpm --registry=http://registry.npm.taobao.org --cache=D:\WebTool\nodejs\node_cache

### ISSUE THREAD

**Issue by taotao365s** [cnpm/cnpm#37]
如果想用原先npm的cache，这里设置是不会生效的。

我看了下config.js文件，可否吧cache字段设置成可配置的？

var config = module.exports = {
  cnpmHost: 'http://npm.taobao.org',
  // cnpmRegistry: 'http://r.cnpmjs.org',
  cnpmRegistry: 'http://registry.npm.taobao.org',
  disturl: 'http://npm.taobao.org/dist', // download dist tarball for node-gyp
  cache: path.join(root, '.npm/.cache_cnpm'),  //cache folder name
  userconfig: path.join(root, '.cnpmrc')
};

**Comment by g8up** [comment]
无法修改 cache，是我的姿势不对吗？
```
C:\Users\Sigma>cnpm set cache d:\.cnpm

C:\Users\Sigma>cnpm config get cache
C:\Users\Sigma\.cnpm
```
不希望 cache 占用我的 C 盘（SSD）

**Comment by fengmk2** [comment]
- npm config get cache
- cnpm config get cache

**Comment by g8up** [comment]
@fengmk2 
```
C:\Users\Sigma>npm config get cache
D:\program files\npm-cache
```
```
C:\Users\Sigma>cnpm config get cache
C:\Users\Sigma\.cnpm
```
