### ISSUE TITLE
可以进行全量同步吗？

### ISSUE THREAD

**Issue by r00t1900** [cnpm/cnpm#370]
可能提到cnpmjs.org比较合适，但是也一样。

## Question
- 是否可以进行npm镜像的全量同步？而不是搭建以后用户访问一次去下载一次，最后慢慢饱和。npmmirror.com早期是怎样同步的呢，也是靠用户的`npm install`去一点一点同步补全的吗？
- npm镜像的全量规模有多大？

**Comment by fengmk2** [comment]
使用 https://github.com/cnpm/cnpmcore 可以进行全量同步，初始化全量包同步脚本可以参考 https://github.com/cnpm/cnpmcore/blob/sync-all-packages/test/SyncAllPackages.ts

**Comment by fengmk2** [comment]
OSS 文件存储到今天为止 22TB
![image](https://user-images.githubusercontent.com/156269/161556526-ae1f2548-70dd-477c-b108-12837cd5e6d2.png)

**Comment by r00t1900** [comment]
> 使用 https://github.com/cnpm/cnpmcore 可以进行全量同步，初始化全量包同步脚本可以参考 https://github.com/cnpm/cnpmcore/blob/sync-all-packages/test/SyncAllPackages.ts

你好，我参考了这个脚本，但是因为不会typescript所以用如下js代码重写了一下：
```javascript
import { load, sync } from "all-package-names";
import urllib from "urllib";

function createTask(url) {
    const result = urllib.request(url, {
      method: 'PUT',
      timeout: 10000,
      dataType: 'json',
      contentType: 'json',
      data: {
        syncDownloadData: true,
        skipDependencies: true,
      },
    });
    return result;
  }

const fullname='hexo-cli';
const url = `https://r.cnpmjs.org/-/package/${fullname}/syncs`;
const result=createTask(url);
const data=result.data;
console.log(data);
```
但是返回结果却是`undefined`，这是什么原因呢？

## more

我参考`SyncAllPackages.ts`后大致清楚全量同步的流程:
### 1 全量获取包名
就是先从`all-package-names`中获取全量名字，然后进行下载同步。获取名字这一部分可以正常获取，当前包数量为`2855155`:
```javascript
import { load, sync } from "all-package-names";

load().then(({ packageNames }) => {
    console.log(packageNames.length); // array of all package names on npm
  });
```

### 2 根据包名进行同步
我不知道可不可以用原始点的方法`npm install <package name>`进行……虽然这样会费点时间，但是在参考代码里我没看到、或者没有成功找到下载存储的部分，望指点，谢谢。

**Comment by r00t1900** [comment]
感谢，官方repo才是最给力的！
