### ISSUE TITLE
sync组件[styled-components]成功但是并没有入库

### ISSUE THREAD

**Issue by zxshang** [cnpm/cnpm#372]
日志参考：
https://npmmirror.com/sync/styled-components?spm=a2c6h.24755359.0.0.569b5d64eXX5Eb#logid=624e8f47e0796d00035cb605

执行完之后搜索组件 styled-components，依然没有

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/styled-components 数据是有的

**Comment by xc13545082723** [comment]
Install fail! Error: [undefined] Can't find package styled-components's version: 5.3.5

**Comment by zxshang** [comment]
https://npmmirror.com/package/styled-components
这里还是搜不到的呢，而且在install的时候，直接就会报这个组件找不到。看是不是哪个同步环节有问题导致并没有真正入库呢

**Comment by Sincenir** [comment]
我这里也遇到的该问题

**Comment by fengmk2** [comment]
已经恢复。

**Comment by lvjiaxuan** [comment]
同样的问题，执行 `cnpm sync` 后，还是查不到。只有通过 web 方式同步，才立即有效。

**Comment by fengmk2** [comment]
安装到最新的 cnpm，会修复 cnpm sync 的问题。
