### ISSUE TITLE
TypeError: randomUUID is not a function

### ISSUE THREAD

**Issue by xsunnydong** [cnpm/cnpm#384]
+ cnpm install
TypeError: randomUUID is not a function
    at formatInstallOptions (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/format_install_options.js:127:33)
    at module.exports (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/local_install.js:54:13)
    at /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js:397:11
npminstall version: 6.3.0
cnpm的依赖npminstall 6.3.0 这一版本有问题  cnpm install 时报错  npminstall 退回到6.2.0版本问题解决  
按照官方文档 https://www.npmjs.com/package/randomuuid randomUUID 在v15.6.0引入 ！
       Polyfill for the crypto.randomUUID() method as proposed in the [WICG randomUUID specification](https://github.com/WICG/uuid) and recently implemented in [Node.js v15.6.0](https://github.com/nodejs/node/pull/36729).

node 版本 v14.5.0
npm 版本  6.14.5
yarn 版本  1.22.4

**Comment by fengmk2** [comment]
请升级到 node 14 的最新版本。

**Comment by xsunnydong** [comment]
大佬， uuid <=3.4.0在2022年6月3日虽被弃用，但高版本如 v7.x.x v8.x.x版本仍旧可用。不考虑沿用老方法的新版本uuid么？
另外 采用randomUUID 实际中 需版本》= v15.6.0 和npminstall 文档里申明支持 Node.js >= 14.x 不符，造成误解。

**Comment by fengmk2** [comment]
@xsunnydong 你去看过 node 14 的官方文档了吗？https://nodejs.org/download/release/latest-v14.x/docs/api/crypto.html#crypto_crypto_randomuuid_options

**Comment by ZOUZDC** [comment]
@fengmk2  Added in: v14.17.0
