### ISSUE TITLE
electron release 历史版本镜像还会更新吗？

### ISSUE THREAD

**Issue by Constaline** [cnpm/cnpm#389]
目前 `https://npmmirror.com/mirrors/electron/` 最低版本是 `v7.3.3`
请问还会同步 electron v1-v7 的历史版本吗？

**Comment by fengmk2** [comment]
历史版本 https://www.electronjs.org/releases/stable 官方已经不再维护，请升级到官方维护的版本，老版本我们不会再去同步了。
