### ISSUE TITLE
https://npmmirror.com/mirrors/node-sass/v4.11.0/win32-x64-83_binding.node 访问内容为空

### ISSUE THREAD

**Issue by liuliangsir** [cnpm/cnpm#392]
截图如下：

![image](https://user-images.githubusercontent.com/8049878/179675441-31a2167b-f244-4463-bdd9-f68760dff785.png)

另外，直接访问 [https://npmmirror.com/mirrors/node-sass/](https://npmmirror.com/mirrors/node-sass/) 会成功跳转；访问不加斜杠的路径，也即 [https://npmmirror.com/mirrors/node-sass](https://npmmirror.com/mirrors/node-sass)，会出现上面类似访问内容为空的问题。

**Comment by fengmk2** [comment]
node-sass 本身就不支持这个 node 的版本 https://github.com/sass/node-sass/releases/tag/v4.11.0
