### ISSUE TITLE
npm同步问题

### ISSUE THREAD

**Issue by jiawei397** [cnpm/cnpm#398]
npm的同步是不是出问题了？同步时间还停留在10月9日。
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/19886374/196099215-78acd864-5fd3-4e12-b1cb-1d157e76ea0e.png">

**Comment by fengmk2** [comment]
出现包版本丢失，请手动执行 cnpm sync

**Comment by jiawei397** [comment]
https://npmmirror.com/这里不是说10分钟同步一次吗？现在不是所有包同步了？

**Comment by fengmk2** [comment]
@jiawei397 最近网络不太好，过一段时间应该就恢复了。
