### ISSUE TITLE
next / pre 版本经常延迟很长时间甚至直接不同步，都要手动点一下 sync 才行

### ISSUE THREAD

**Issue by exherb** [cnpm/cnpm#400]
比如 https://npmmirror.com/package/@vuepress/cli/v/2.0.0-beta.52?spm=a2c6h.24755359.0.0.42a94d03YKW8AV&file=2.0.0-beta.52 的 2.0 beta 版本

**Comment by fengmk2** [comment]
同一个问题 https://github.com/cnpm/cnpmcore/issues/343

**Comment by fengmk2** [comment]
关于同步延迟，这个目前已经恢复。
