### ISSUE TITLE
angular的library下，引入@types/d3，compile时报错d3类型定义缺失

### ISSUE THREAD

**Issue by oushu1tangxiangyue1** [cnpm/cnpm#410]
@types/d3中，node_modules下未正确链接。
![企业微信截图_1cfa379e-6fc7-4d53-bd38-5be3f9222725](https://user-images.githubusercontent.com/85913504/233050969-22915bd2-ae17-4974-a91e-6a0e69900039.png)

@types/d3/package.json文件中指定的依赖列表。
![企业微信截图_3eccb552-4bbc-4cf0-9595-b2a4130dbc15](https://user-images.githubusercontent.com/85913504/233050765-4c1a6c83-17b9-4559-9542-11d443c3d9f9.png)

@types/d3/index.d.ts中的类型定义。
![企业微信截图_b00003b6-1cb4-4627-a238-08a096b43ad5](https://user-images.githubusercontent.com/85913504/233051753-bd1fed36-6462-43ac-b145-9f9030c7d766.png)

**Comment by fengmk2** [comment]
能否提供一个复现的代码库？

**Comment by oushu1tangxiangyue1** [comment]
cnpm install @types/d3任意版本即可复现

**Comment by fengmk2** [comment]
@oushu1tangxiangyue1 node_modules/.store/@types+d3@7.4.0/node_modules/@types 在这个目录下，看看能否找到。

**Comment by oushu1tangxiangyue1** [comment]
该目录下，以及.store下存在这些types定义
![image](https://user-images.githubusercontent.com/85913504/233537300-02447fc3-8546-4df0-a330-f13f7f1a0f70.png)

然而，在compile时，代码中的ts类型检查会报错，必须在项目中的package.json中明文引入这些各个模块的@types依赖，而不能仅引入@types/d3。但使用npm时是可以仅引入@types/d3的，无需明文引入各模块。
![企业微信截图_46a17f83-2c22-4dbd-8830-2a49741a84a4](https://user-images.githubusercontent.com/85913504/233537774-21a54f4d-3f8a-4f58-ae2e-8e424abded23.png)
![企业微信截图_8369998e-a3aa-4d1f-a477-58431d7b54de](https://user-images.githubusercontent.com/85913504/233538074-a7f545f1-d642-45f7-955b-5a3e53ad8cb9.png)

我使用的angular框架，在ts文件中以import * as d3 from 'd3';的方式使用。

**Comment by fengmk2** [comment]
@oushu1tangxiangyue1 最近修复了一个 bug https://github.com/cnpm/npminstall/pull/454 ，你重新安装 cnpm 然后试试看。

**Comment by oushu1tangxiangyue1** [comment]
当前场景下，重装cnpm并重新下载node_modules后，报错信息没有发生变化

**Comment by fengmk2** [comment]
@oushu1tangxiangyue1 能否提供一个最小可复现代码库，我对 d3 不熟悉，比较难造这个复现的过程。

**Comment by oushu1tangxiangyue1** [comment]
https://github.com/txy900310/cnpm-d3-debug
我之前描述的不够精确，抱歉。在angular的library中才会出现此类情况。
该repo下`cnpm install`，然后`cnpm run build`即可复现。

**Comment by fengmk2** [comment]
![image](https://user-images.githubusercontent.com/156269/233790267-3b85d195-31eb-4bd8-b89d-691bb2f89caf.png)
这些依赖目前是没有的，看起来是依赖了 npm 的默认幽灵依赖模式。我使用 pnpm 来测试你提供的 repo 也是报一样的错误。
