### ISSUE TITLE
npm init vue@latest创建的vue项目中， 运行vue-tsc报错

### ISSUE THREAD

**Issue by Caffeine19** [cnpm/cnpm#412]
我通过npm init vue@latest 创建的vue项目中，使用cnpm 安装了依赖。
在运行npm run type check的时候，出现了如下关于vue-tsc的报错
<img width="1300" alt="Snipaste_2023-04-24_19-24-29" src="https://user-images.githubusercontent.com/108726581/233983800-96e697ed-81c1-4763-b675-06b242a11234.png">
<img width="1497" alt="Snipaste_2023-04-24_19-24-11" src="https://user-images.githubusercontent.com/108726581/233983827-5dea277a-6073-4e4f-aa87-1f40fcb220aa.png">
之前一直没有问题，直到昨天手贱把依赖删了重新安装时发现了问题
<img width="636" alt="iShot_2023-04-24_19 31 35" src="https://user-images.githubusercontent.com/108726581/233984323-f5837c66-b15b-4e23-8402-5d517f03644b.png">

我下午的时候尝试过yarn，是没有问题的，刚刚用pnpm测试了一下，也没有问题。

**Comment by fengmk2** [comment]
@Caffeine19 cnpm -v 执行一下，看看版本信息。

**Comment by Caffeine19** [comment]
> @Caffeine19 cnpm -v 执行一下，看看版本信息。

![image](https://user-images.githubusercontent.com/108726581/234176224-99fd0b94-5d28-4c35-aa44-9f1f7ef41800.png)

这是我在这台windows上的信息，同样也在运行vue-tsc时候报错，mac的话等下晚点添加上

**Comment by fengmk2** [comment]
@Caffeine19 重新安装一下 cnpm，然后再试试看，最近 npminstall 发布了一个 bugfix 版本。
