### ISSUE TITLE
npmmirror的node镜像缺少SHASUMS256文件

### ISSUE THREAD

**Issue by igoray** [cnpm/cnpm#418]
<img width="482" alt="image" src="https://github.com/cnpm/cnpm/assets/27860050/1acbb57b-24b9-4fdd-95be-4a21e4db7ff0">

https://cdn.npmmirror.com/binaries/node/latest/SHASUMS256.txt

如上文件是空的

**Comment by fengmk2** [comment]
感谢反馈，正在重新同步 https://r.cnpmjs.org/binary.html?path=node/latest/

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/binary.html?path=node/latest/ 已经重新同步。
