### ISSUE TITLE
使用npm node14.18.0版本全局安装cnpm报错

### ISSUE THREAD

**Issue by xiguachao** [cnpm/cnpm#423]
使用管理员打开 powershell 安装都报错 
![image](https://github.com/cnpm/cnpm/assets/99702809/dcca90e5-e5e1-4061-824f-b53c0888c291)
请问大佬怎么解决

**Comment by fengmk2** [comment]
@xiguachao 可以通过下面方式尝试一下，先安装 npminstall，然后通过它来安装 cnpm。

```bash
npm i npminstall -g --registry=https://registry.npmmirror.com
npminstall -g cnpm -c
```

**Comment by xiguachao** [comment]
> @xiguachao 可以通过下面方式尝试一下，先安装 npminstall，然后通过它来安装 cnpm。
> 
> ```shell
> npm i npminstall -g --registry=https://registry.npmmirror.com
> npminstall -c -g cnpm
> ```
![image](https://github.com/cnpm/cnpm/assets/99702809/36d0848b-c39b-4e40-b461-65562065a1a5)
使用的就是淘宝镜像

**Comment by xiguachao** [comment]
> @xiguachao 可以通过下面方式尝试一下，先安装 npminstall，然后通过它来安装 cnpm。
> 
> ```shell
> npm i npminstall -g --registry=https://registry.npmmirror.com
> npminstall -c -g cnpm
> ```

![image](https://github.com/cnpm/cnpm/assets/99702809/c789efc1-a74b-4181-a254-5faf0b21a472)
为什么无法识别呢

**Comment by fengmk2** [comment]
Windows 我没有环境，可以试试这个方式 https://www.yuque.com/egg/cnpm/rgrenam32us7n3xu#Papoj

**Comment by zhengyu23** [comment]
难兄难弟

**Comment by zhengyu23** [comment]
**版本问题。** 安装cnpm时，没有指定版本，则默认安装最新版cnpm，但旧版npm不能适配最新版cnpm，所以安装失败。但因为 node 给出的报错都很奇奇怪怪，所以才误导那么多人。

**解决办法：下载对应npm版本的cnpm。** 题主node版本为14.18，对应npm版本为6.14，应该下载7.11版本的cnpm，如下：
 `npm install -g cnpm@7.1.1 --registry=https://registry.npmmirror.com`

_解决办法参考资料：https://blog.csdn.net/qq_39006954/article/details/130632763
cnpm安装版本参考：https://blog.csdn.net/mrmodel665/article/details/134556089_
