### ISSUE TITLE
cnpm@7版本无缘无故修改了版本号，没有按照package.json的文件中的版本号走

### ISSUE THREAD

**Issue by djkloop** [cnpm/cnpm#425]
cnpm@7版本无缘无故修改了版本号，没有按照package.json的文件中的版本号走，把package.json锁了版本也不行

![image](https://github.com/cnpm/cnpm/assets/21050914/4b6e167d-37db-44cf-aa58-b05ea0ac41b0)

![image](https://github.com/cnpm/cnpm/assets/21050914/cce636ae-a480-434c-a82c-8620631025ec)

##### package.json 文件
![image](https://github.com/cnpm/cnpm/assets/21050914/344ee959-6f78-4a4c-9ee2-75a3d89fe13b)

#### cnpm 信息
![image](https://github.com/cnpm/cnpm/assets/21050914/7600c46b-6c68-4005-8309-1853744c9111)

**Comment by fengmk2** [comment]
给一个可以重现的 package.json?

**Comment by djkloop** [comment]
@fengmk2 

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@logicflow/core": "^1.1.31",
    "@logicflow/extension": "^1.1.31"
  }
}
```
##### 安装的包
![image](https://github.com/cnpm/cnpm/assets/21050914/f803698b-a2d3-4950-bb6d-49fe92f64f17)

##### 操作步骤
![image](https://github.com/cnpm/cnpm/assets/21050914/f996a6aa-3972-4f59-8682-88f4a00ce890)

**Comment by fengmk2** [comment]
node_modules/@logicflow/core 这个版本是正确的就行，下划线开头的版本是 npminstall 的安装机制，你可以忽略。

**Comment by djkloop** [comment]
@fengmk2 可是现在安装完之后项目会引用高版本的core....会报错...
