### ISSUE TITLE
poi 的二进制镜像的 exe 文件未被同步

### ISSUE THREAD

**Issue by KochiyaOcean** [cnpm/cnpm#435]
https://registry.npmmirror.com/binary.html?path=poi/v11.0.0-beta.4/

v11.0.0-beta.2 ~ beta.4 版本的 exe 文件未被正确同步
![image](https://github.com/cnpm/cnpm/assets/8194131/4d8e2cdf-9b2e-44b4-a49d-879d8324d8c8)
![image](https://github.com/cnpm/cnpm/assets/8194131/8b8891a0-ef14-4b9d-9de9-8dd5c6975f9b)

**Comment by fengmk2** [comment]
OK，我重新同步一次

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmcore/blob/master/app/common/adapter/binary/GithubBinary.ts#L44 
![image](https://github.com/cnpm/cnpm/assets/156269/7d295180-ccab-47ef-b878-64611d439b29)
超过了我们的默认大小限制，我加大到 250 MB 吧

**Comment by fengmk2** [comment]
已发起重新同步，预计1小时后完成。

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/-/binary/poi/v11.0.0-beta.4/poi-setup-11.0.0-beta.4.exe

已经重新同步完成。
