### ISSUE TITLE
Prisma 的二进制镜像 404

### ISSUE THREAD

**Issue by VxRain** [cnpm/cnpm#436]
安装依赖后执行 `prisma generate`，会报 404。

环境变量为：`PRISMA_ENGINES_MIRROR=https://registry.npmmirror.com/-/binary/prisma`，
错误提示：
 > Downloading Prisma engines for Node-API for debian-openssl-3.0.x [                    ] 0%Error: Failed to fetch sha256 checksum at https://registry.npmmirror.com/-/binary/prisma/all_commits/0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5/debian-openssl-3.0.x/schema-engine.sha256 - 404 Not Found
If you need to ignore this error (e.g. in an offline environment), set the PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING environment variable to a truthy value.
Example: PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1

再设置环境变量：`PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1`
错误提示：
> Downloading Prisma engines for Node-API for debian-openssl-3.0.x [                    ] 0%Error: Failed to fetch the engine file at https://registry.npmmirror.com/-/binary/prisma/all_commits/0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5/debian-openssl-3.0.x/libquery_engine.so.node.gz - 404 Not Found

**Comment by fengmk2** [comment]
prisma 没有很好的同步方式，没法同步它的全量 commits

**Comment by VxRain** [comment]
> prisma 没有很好的同步方式，没法同步它的全量 commits

我按照 https://github.com/cnpm/cnpmcore/issues/473#issuecomment-1562115738 的逻辑跟了一下，应该能被同步才对
版本号5.7.1，https://registry.npmmirror.com/@prisma/engines/5.7.1/files/package.json

**Comment by fengmk2** [comment]
嗯，可以试试看

**Comment by VxRain** [comment]
> 嗯，可以试试看

你是要尝试重新同步一下吗？

**Comment by VxRain** [comment]
补充下，https://github.com/cnpm/cnpmcore/issues/473#issuecomment-1562115738 示例中 4.14.1 版本的 @prisma/engines-version 是在 devDependencies 中，5.7.1 的是在 dependencies 中，不知道会影响判断逻辑吗？

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmcore/pull/474/files#diff-6dc23c3f5db0879789c7e4a9765fa9fef1a6e3486fba633f75538ad0ce4a6ffcR39

看起来还需要兼容一下

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/@prisma/engines/5

**Comment by fengmk2** [comment]
大概1小时后再来看看，应该就同步了

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/-/binary/prisma/all_commits/0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5/debian-openssl-3.0.x/  已同步完成

**Comment by VxRain** [comment]
> https://registry.npmmirror.com/-/binary/prisma/all_commits/0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5/debian-openssl-3.0.x/  已同步完成

感谢❤️，测试已经可以了。
