### ISSUE TITLE
SSL证书过期，望周知

### ISSUE THREAD

**Issue by JZDKG** [cnpm/cnpm#438]
![image](https://github.com/cnpm/cnpm/assets/38561565/8cfda67e-87e8-43f1-9453-0f744f87d281)

**Comment by liangxin0527** [comment]
俺也一样

**Comment by fengmk2** [comment]
npm 淘宝镜像域名证书正式过期，大家还在使用淘宝域名的请迁移到新域名 https://registry.npmmirror.com/

https://zhuanlan.zhihu.com/p/465424728

**Comment by fengmk2** [comment]
如果还有依赖 nvm 老版本的，可以设置环境变量

```
NODEJS_ORG_MIRROR=https://cdn.npmmirror.com/binaries/node
```

**Comment by JZDKG** [comment]
> 如果还有依赖 nvm 老版本的，可以设置环境变量
> 
> ```
> NODEJS_ORG_MIRROR=https://cdn.npmmirror.com/binaries/node
> ```

感谢回复

**Comment by liangxin0527** [comment]
https://npm.taobao.org/mirrors/sentry-cli 这个包切换域名下载不下来。提示404

**Comment by fengmk2** [comment]
> https://npm.taobao.org/mirrors/sentry-cli 这个包切换域名下载不下来。提示404

这个之前也没有啊

**Comment by liangxin0527** [comment]
这个sentry我们淘宝是有的。现在将协议改成http还是可以下载的。但是使用https 是不可以的

**Comment by liangxin0527** [comment]
顺便问一下 http://npm.taobao.org 这个域名后期会下线吗。后期只在npmmirror维护吗？

**Comment by fengmk2** [comment]
> 顺便问一下 http://npm.taobao.org 这个域名后期会下线吗。后期只在npmmirror维护吗？

它是已经 301 跳转到 https://npmmirror.com 了，域名解析也会在未来下线。

```bash
curl -v http://npm.taobao.org                                  
*   Trying 114.55.80.225:80...
* Connected to npm.taobao.org (114.55.80.225) port 80
> GET / HTTP/1.1
> Host: npm.taobao.org
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.18.0 (Ubuntu)
< Date: Tue, 23 Jan 2024 02:44:09 GMT
< Content-Type: text/html
< Connection: keep-alive
< Location: https://npmmirror.com/
< Strict-Transport-Security: max-age=15768000
< Via: npmmirror.com-03
< Content-Length: 178
```

**Comment by fengmk2** [comment]
> 这个sentry我们淘宝是有的。现在将协议改成http还是可以下载的。但是使用https 是不可以的

会在 https://github.com/cnpm/cnpmcore/issues/643 修复

**Comment by fengmk2** [comment]
@liangxin0527 我看有的

html https://npmmirror.com/mirrors/sentry-cli/2.26.0/
api https://registry.npmmirror.com/-/binary/sentry-cli/2.26.0/
