### ISSUE TITLE
npm.taobao.org cert has expired !!!!

### ISSUE THREAD

**Issue by tclxsr** [cnpm/cnpm#439]
error /Users/***/node_modules/@sentry/cli: Command failed.
Exit code: 1
Command: node ./scripts/install.js
Arguments:
Directory: /Users/***/node_modules/@sentry/cli
Output:
[sentry-cli] Downloading from https://cdn.npm.taobao.org/dist/sentry-cli/1.77.3/sentry-cli-Darwin-universal
Error: Unable to download sentry-cli binary from https://cdn.npm.taobao.org/dist/sentry-cli/1.77.3/sentry-cli-Darwin-universal.
Error code: CERT_HAS_EXPIRED

**Comment by fengmk2** [comment]
change `sentrycli_cdnurl=https://npm.taobao.org/mirrors/sentry-cli` to `sentrycli_cdnurl=https://npmmirror.com/mirrors/sentry-cli`
