### ISSUE TITLE
ssl证书过期：https://registry.npm.taobao.org/

### ISSUE THREAD

**Issue by forkyguo** [cnpm/cnpm#441]

**Comment by rustyhu** [comment]
[新的Web 站点：https://npmmirror.com，Registry Endpoint：https://registry.npmmirror.com。随着新的域名已经正式启用，老 http://npm.taobao.org 和 http://registry.npm.taobao.org 域名将于 2022 年 05 月 31 日零时起停止服务。](https://developer.aliyun.com/article/801527)
