### ISSUE TITLE
下载node-sass包404

### ISSUE THREAD

**Issue by wallfacers** [cnpm/cnpm#445]
报错日志

[INFO] Downloading binary from https://registry.npmmirror.com/node-sass/v4.13.1/linux-x64-72_binding.node
[ERROR] Cannot download "https://registry.npmmirror.com/node-sass/v4.13.1/linux-x64-72_binding.node": 
[ERROR] 
[ERROR] HTTP error 404 Not Found
[ERROR] 
[ERROR] Hint: If github.com is not accessible in your location
[ERROR]       try setting a proxy via HTTP_PROXY, e.g. 
[ERROR] 
[ERROR]       export HTTP_PROXY=http://example.com:1234/
[ERROR] 
[ERROR] or configure npm proxy via
[ERROR] 
[ERROR]       npm config set proxy http://example.com:8080/

在npmmirror中进行了同步
![image](https://github.com/cnpm/cnpm/assets/26599681/e77a890b-fe48-420c-82ac-d0c541a84262)

https://cdn.npmmirror.com/packages/node-sass/syncs/2024/04/161408-661e15ce367876ec3a0437ff.log

目前还是404感觉包没同步过来

华为云这边是有这个包的
https://mirrors.huaweicloud.com/node-sass/v4.13.1/linux-x64-72_binding.node

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/binary.html?path=node-sass/v4.13.1/

地址是这里

**Comment by fengmk2** [comment]
通过环境变量安装

```bash
SASS_BINARY_SITE=https://cdn.npmmirror.com/binaries/node-sass npm i node-sass
```

https://github.com/cnpm/binary-mirror-config/blob/master/package.json#L58C10-L58C74

**Comment by wallfacers** [comment]
@fengmk2  谢谢，设置SASS_BINARY_SITE果然好使了，不过我有个疑问，这个路径是最近调整的吗，以前使用是可以的"https://registry.npmmirror.com/node-sass/v4.13.1/linux-x64-72_binding.node":

**Comment by fengmk2** [comment]
> @fengmk2 谢谢，设置SASS_BINARY_SITE果然好使了，不过我有个疑问，这个路径是最近调整的吗，以前使用是可以的"https://registry.npmmirror.com/node-sass/v4.13.1/linux-x64-72_binding.node":

没有的，一直不可以。
