### ISSUE TITLE
npm registry TLS certificate expired 

### ISSUE THREAD

**Issue by BubbleBear** [cnpm/cnpm#446]
I believe that the TLS certificate for `npm.taobao.org` domain has just expired, which results in *npm install failure

<img width="563" alt="image" src="https://github.com/cnpm/cnpm/assets/17879773/a2b60dc7-36d6-4879-80f8-ed29037df2f6">

**Comment by fengmk2** [comment]
Please use https://registry.npmmirror.com instead
