### ISSUE TITLE
Bug：无法同步 ajv 模块

### ISSUE THREAD

**Issue by guojingkang** [cnpm/cnpm#449]
<img width="1432" alt="image" src="https://github.com/cnpm/cnpm/assets/39728127/4d3d5955-fd46-4d50-94ee-54b9713b9b16">
<img width="1123" alt="image" src="https://github.com/cnpm/cnpm/assets/39728127/1a2c7651-f604-48cf-acbc-b801cac86a50">
<img width="1634" alt="image" src="https://github.com/cnpm/cnpm/assets/39728127/0901b5d1-6d7b-4fca-ae0a-ac5c22e6afe5">

npm官网上的ajv模块最新的是6月4日更新的 8.15 版本，npmmirror上的版本最新的是 8.14，重新 sync 后也无效

**Comment by fengmk2** [comment]
https://github.com/cnpm/bug-versions/pull/251 因为这个
