### ISSUE TITLE
windows下cnpm install -g路径问题

### ISSUE THREAD

**Issue by zjgnlzq** [cnpm/cnpm#45]
用```npm install -g```  安装路径是C:\Users\username\AppData\Roaming\npm\，但是用cnpm安装时候路径跑到我的node.js安装路径下去了，觉得很怪

**Comment by fengmk2** [comment]
`npm config ls -l` 看一下 `prefix` 配置就知道

**Comment by zjgnlzq** [comment]
prefix的配置看到是node的安装目录，但是我觉得用cnpm和用原始的npm，行为保持一致比较合理

**Comment by fengmk2** [comment]
这是npm的行为，你本地的npm版本比较旧，cnpm里面带的npm比较新

**Comment by zjgnlzq** [comment]
恩

**Comment by liyuan-rey** [comment]
如果没有手工指定的话，windows 系统中安装的 npm 2.x 或 3.x 都默认带有一个全局配置文件，在：
```
%appdata%\npm\node_modules\npm\npmrc
```
或者
```
<path-to-node.exe>\node_modules\npm\npmrc
```
windows 系统中这个文件里会重新定义 `prefix` 参数，一般是指向 `%appdata%\npm`

**Comment by fengmk2** [comment]
我回去删除cnpmrc 看看是否能解决问题
