### ISSUE TITLE
Missing canvas binary

### ISSUE THREAD

**Issue by taoqf** [cnpm/cnpm#450]
ERR! install response status 404 Not Found on https://registry.npmmirror.com/-/binary/canvas/v2.11.2/canvas-v2.11.2-node-v115-linux-musl-x64.tar.gz

node v20.14.0 lts

**Comment by fengmk2** [comment]
Please provide a way to reproduce it

**Comment by taoqf** [comment]
```dockerfile
FROM node:lts-alpine
yarn add canvas
```

**Comment by taoqf** [comment]
Sorry I mean alpine, lts is ok.

**Comment by fengmk2** [comment]
https://github.com/Automattic/node-canvas/releases/tag/v2.11.2

canvas-v2.11.2-node-v115-linux-musl-x64.tar.gz is not exists on canvas releases assets.

**Comment by taoqf** [comment]
Sorry. here is the solution. https://github.com/Automattic/node-canvas/pull/2370
