### ISSUE TITLE
npmmirror.com 上 peacenotwar 包丢失

### ISSUE THREAD

**Issue by yejimeiming** [cnpm/cnpm#452]
<img width="884" alt="image" src="https://github.com/user-attachments/assets/f28d3bf8-6c53-458d-abc1-d43d92cf06d3">
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/23547935-ddeb-4a77-a629-701b2f52311a">

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/peacenotwar 是被 blocked 了
