### ISSUE TITLE
建立自己的私有源需要的硬件设备条件

### ISSUE THREAD

**Issue by ilife5** [cnpm/cnpm#50]
我们想在公司内部搭建私有源，请问服务器需要的硬盘空间需要多大。以现在的经验，机器的配置有没有什么要求。

**Comment by fengmk2** [comment]
使用标准的模式，只需要考虑私有包空间即可，普通几g的存储就足够用了，不需要全量同步的。

**Comment by ilife5** [comment]
弱弱问一句，taobaonpm是全量同步了么？用了多大的空间呢？

**Comment by fengmk2** [comment]
taobaonpm 的 oss 没法统计，不过我可以给你看 cnpm 的 qiniu 云存储占用 300G，不过包含了 http://cnpmjs.org/mirrors node 和 iojs 等二进制包的镜像文件。

![image](https://cloud.githubusercontent.com/assets/156269/6827635/90867c24-d343-11e4-8d65-28c5df31c515.png)

总体来说，250GB 的大小还是有的。

@ilife5

**Comment by fengmk2** [comment]
至于服务器，cnpmjs.org 之前是放在 do 的 512MB 的最低配服务器上运行的，mysql 也是 do 的512MB 内存的最低配服务。

所以几乎没有硬件要求，对于小团队，单机版 sqlite 的方案就足够了，能保证 sqlite 定时备份就能保证数据完整性了。

**Comment by ilife5** [comment]
@fengmk2 非常感谢提供这些信息

**Comment by fengmk2** [comment]
不客气，如果你真的会使用 cnpm部署私有 npm，遇到任何技术问题，都可以给我们提 issue，我一般晚上看到都会及时回复解答。

**Comment by ilife5** [comment]
@fengmk2 好的，谢谢
