### ISSUE TITLE
运行几次显示信息都报错了,是bug?

### ISSUE THREAD

**Issue by chapgaga** [cnpm/cnpm#54]
运行多次了

npm info atom-package-manager
npm http GET http://registry.npm.taobao.org/atom-package-manager
npm http 200 http://registry.npm.taobao.org/atom-package-manager
**npm ERR! registry error parsing json**
npm ERR! SyntaxError: Unexpected end of input
npm ERR! {"_id":"atom-package-manager","_rev":"815255","name":"atom-package-m
n":"Atom package manager","dist-tags":{"latest":"0.158.0"},"maintainers":[{"n
il":"ogle.ben@gmail.com"},{"name":"izuzak","email":"izuzak@gmail.com"},{"name
mail":"kevinsawicki@gmail.com"},{"name":"nathansobo","email":"nathan@github.c
blycorey","email":"probablycorey@gmail.com"},{"name":"zcbenz","email":"zcbenz
":{"modified":"2015-04-02T02:18:32.000Z","created":"2014-04-24T21:21:27.392Z"

**Comment by luqin** [comment]
我也遇到过一次

**Comment by fengmk2** [comment]
安装的是那个包呢？

**Comment by fengmk2** [comment]
按 `npm ERR! SyntaxError: Unexpected end of input` 错误信息看来，是 atom-package-manager 这个包的 json 信息没用下载完整

**Comment by chapgaga** [comment]
@fengmk2 为何下载不完整?试了多次还是不行啊

**Comment by fengmk2** [comment]
我执行是 ok 的 

```bash
cnpm info atom-package-manager
 
{ name: 'atom-package-manager',
  description: 'Atom package manager',
  'dist-tags': { latest: '1.0.1' },
  maintainers: 
   [ 'benogle <ogle.ben@gmail.com>',
     'izuzak <izuzak@gmail.com>',
     'kevinsawicki <kevinsawicki@gmail.com>',
     'nathansobo <nathan@github.com>',
     'probablycorey <probablycorey@gmail.com>',
     'zcbenz <zcbenz@gmail.com>' ],
  time: 
   { modified: '2015-06-23T00:37:30.000Z',
     created: '2014-04-24T21:21:27.392Z',
     '1.0.1': '2015-06-22T22:36:47.863Z',
     '0.171.0': '2015-06-04T21:07:18.396Z',
     '0.170.0': '2015-06-04T17:46:44.437Z',
     '0.169.0': '2015-06-03T17:58:42.270Z',
     '0.168.0': '2015-05-20T01:44:34.851Z',

```
