### ISSUE TITLE
cnpm无法正确同步npm的jquery（全小写）包

### ISSUE THREAD

**Issue by liyuan-rey** [cnpm/cnpm#59]
cnpm无法正确同步npm的jquery（全小写）包

npm上有两个很相近的包，一个是jQuery另一个是jquery，两个包名只有大小写的区分

jQuery包的地址是：https://www.npmjs.com/package/jQuery
jquery包的地址是：https://www.npmjs.com/package/jquery

cnpm在同步时会把他们弄混，同步操作会执行完成，但却无法得到正确的结果。

**Comment by fengmk2** [comment]
呃，狗血，我回去重新同步一下

**Comment by fengmk2** [comment]
@liyuan-rey 请使用 http://npm.taobao.org/package/jquery 这个吧。jQuery 这个包只能忽略了，没必要使用它。
