### ISSUE TITLE
yo 搜索 generator 时出错

### ISSUE THREAD

**Issue by sxd1140** [cnpm/cnpm#60]
使用 cnpm 仓库 出错
/usr/local/lib/node_modules/yo/lib/routes/install.js:22
        throw err;
              ^
GotError: http://r.cnpmjs.org/-/_view/byKeyword?startkey=[%22yeoman-generator%22]&endkey=[%22yeoman-generator%22,%7B%7D]&group_level=3 response code is 404 (Not Found)

使用 官方 仓库 正常

**Comment by fengmk2** [comment]
不支持搜索。
