### ISSUE TITLE
安装cordova跟ionic出错

### ISSUE THREAD

**Issue by ramsaylee** [cnpm/cnpm#65]
Hi,

这两天尝试安装cordova跟ionic的时候，一直报错，会报两种错误：
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/i/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/Users/i/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/pangyp/bin/node-gyp.js" "install" "-g" "cordova" "ionic"
npm ERR! node v0.12.2
npm ERR! npm  v2.13.5

npm ERR! Cannot read property 'emit' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.2","npm":"2.13.5"})

--------------另一个错误--------------
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.2","npm":"2.13.5"})
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/i/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/Users/i/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/pangyp/bin/node-gyp.js" "install" "-g" "cordova" "ionic"
npm ERR! node v0.12.2
npm ERR! npm  v2.13.5
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

不知道是什么原因，安装其他包都是没有问题的，例如gulp, npm本身等。
试了好多次都是这样，上海电信，宽带通都是这样，麻烦帮忙看看，非常感谢！

**Comment by fengmk2** [comment]
加个 --loglevel=http 参数看看

**Comment by ramsaylee** [comment]
@fengmk2 谢谢你的及时回复，我之后还尝试了上海移动的网络也是不行，一直报超时。最后我是直接找朋友借了个VPN（我自己平时用的是shadowsocks），连上VPN使用sudo npm install -g cordova ionic来安装的，现在没有什么问题了。所以可能还是跟网络有关系。谢谢！

**Comment by fengmk2** [comment]
如果是模块自行的安装逻辑，cnpm是无法代理的
