### ISSUE TITLE
There is space on path when use cnpm on windows through Error

### ISSUE THREAD

**Issue by xiaoxinw** [cnpm/cnpm#67]
Here is the message when I try to install a module locally.

node version v0.4.0

Error: Cannot find module 'D:\Program'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_global\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\junzhe\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=C:\\Users\\junzhe\\.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=D:\\Program Files\\nodejs\\node_global\\node_modules\\cnpm\\node_modules\\pangyp\\bin\\node-gyp.js" "install" "mmmagic"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! mmmagic@0.3.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmmagic@0.3.15 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mmmagic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mmmagic
npm ERR! There is likely additional logging output above.

**Comment by fengmk2** [comment]
Can you tell me the module name?

**Comment by fengmk2** [comment]
Please use cnpm@3.2.2 and try again

**Comment by xiaoxinw** [comment]
ok, the module is mmmagic , I will have a try later ,thank u
