### ISSUE TITLE
node_modules 包铺平

### ISSUE THREAD

**Issue by ahan** [cnpm/cnpm#73]
cnpm 能像 npm 一样安装完依赖包，依赖包是铺平的吗？
![image](https://cloud.githubusercontent.com/assets/654880/10417028/8ce058fa-7060-11e5-8892-77afc00a2c01.png)

详见：https://cnodejs.org/topic/55beec03f36f579657fc56d9

我用的是：
node@4.1.2
npm@3.3.6
cnpm@3.2.3
OSX EI Captain

**Comment by fengmk2** [comment]
请使用 cnpm@beta

```bash
$ cnpm i -g cnpm@beta
```
