### ISSUE TITLE
cnpm -g安装后组件找不到

### ISSUE THREAD

**Issue by fsy0718** [cnpm/cnpm#80]
* 系统环境:  os X El Capitan 10.11.1
* node: v5.0.0
* cnpm: 3.3.1

node是通过homebrew安装的，npm是通过homebrew安装node时自动安装的
cnpm 是通过`npm install -g cnpm --registry=https://registry.npm.taobao.org`进行替换的；

 `sudo cnpm install -g webpack` 后，运行`webpack`，显示 `-bash: webpack: command not found`

`cnpm config get prefix`  =》 `/usr/local/Cellar/node/5.0.0`
`npm config get prefix` => `/usr/local`
由于这个的设置不一样，导致 `/usr/local/bin` 中无webpack，期望通过  `npm install -g cnpm --registry=https://registry.npm.taobao.org` 能自动设置prefix 或者提示设置

**Comment by alsotang** [comment]
这种情况，去 homebrew 那边建议一下，让它把 `/usr/local/Cellar/node/5.0.0` 下面对应的 node 的 bin 目录自动加入 $PATH 中。

不过 homebrew 做这个事情也说不上合适。手动设置一下就好了。cnpm 反正不适合做这个事情。
