### ISSUE TITLE
How to deal with download the the build source file blocked?

### ISSUE THREAD

**Issue by leecade** [cnpm/cnpm#86]
Many packages need to download source file from blocked url for build, for example:

`install.js` from https://github.com/imagemin/optipng-bin

```js
'use strict';

var BinBuild = require('bin-build');
var log = require('logalot');
var bin = require('./');

bin.run(function (err) {
	if (err) {
		log.warn(err.message);
		log.warn('optipng pre-build test failed');
		log.info('compiling from source');

		new BinBuild()
			.src('http://downloads.sourceforge.net/project/optipng/OptiPNG/optipng-0.7.5/optipng-0.7.5.tar.gz')
			.cmd([
				'./configure --with-system-zlib --prefix="' + bin.dest() + '"',
				'--bindir="' + bin.dest() + '"'
			].join(' '))
			.cmd('make install')
			.run(function (err) {
				if (err) {
					log.error(err.stack);
					return;
				}

				log.success('optipng built successfully');
			});

		return;
	}

	log.success('optipng pre-build test passed successfully');
});
```

As we know, `sourceforge.net` is out of GFW, so we will got the build error.

**Comment by alsotang** [comment]
这是个别包的以来问题，已经不是 cnpm 能处理的范畴了

2015-12-27 23:09 GMT+08:00 斯人 <notifications@github.com>:

**Comment by leecade** [comment]
@alsotang 是我知道这个问题比较麻烦, 讨论一下, 可以通过

1. `sub_filter` 将 `http://downloads.sourceforge.net` -> `http://downloads.sourceforge.taobao.net `

2. `downloads.sourceforge.taobao.net ` 反代 `sourceforge.net`

解决吗

**Comment by alsotang** [comment]
淘宝怎么可能为整个 sf 做翻墙。。。。。。
而且，我们也不可能从代码里面抽出 sf 的地址来，替换成 taobao 的啊。

这种涉及图像处理的包，一个两个都是要编译的。你还是翻墙解决吧。


2015-12-29 7:50 GMT+08:00 斯人 <notifications@github.com>:

**Comment by leecade** [comment]
只是反代不是镜像整个

**Comment by dead-horse** [comment]
@leecade 淘宝的这个镜像就是阿里云的机器而已，他帮你反向代理了也照样无法下载，除非镜像回来

**Comment by dead-horse** [comment]
https://npm.taobao.org/mirrors  我们已经有了很多的镜像了，如果确实有价值我们是可以帮忙加的。

**Comment by fengmk2** [comment]
@leecade optipng 是很常用的吗？是的话，可以做 mirror

**Comment by leecade** [comment]
@fengmk2 我的意思是系统性的解决这个问题, 反代 http://downloads.sourceforge.net/project/optipng/OptiPNG/optipng-0.7.5/optipng-0.7.5.tar.gz, 然后 `sub_filter` 来替代地址, @dead-horse 解释了阿里没法提供海外服务器, 那么反代就无法做了

**Comment by alsotang** [comment]
实现起来哪有这么容易啊，去 hook node 的 http 接口吗？

2016-01-04 15:02 GMT+08:00 斯人 <notifications@github.com>:
