### ISSUE TITLE
目前搭建私有cnpm的总数据量是否可以做清理？

### ISSUE THREAD

**Issue by adaiguoguo** [cnpm/cnpm#88]
目前搭建私有cnpm的总数据量为443G,特请教大神能否有一些策略去做一些清理？

**Comment by alsotang** [comment]
全量同步才有这么大吧？

![image](https://cloud.githubusercontent.com/assets/1147375/12106916/52d54170-b39f-11e5-90b5-8ed81305c8d1.png)

可以按需同步的啊

**Comment by adaiguoguo** [comment]
看了下确实做了全量，推荐是用exist模式吗？

**Comment by alsotang** [comment]
我这边腾讯内部的 cnpm 反正是 exist 模式的。目前运行了三个月左右，不超过50g。

2016-01-05 14:14 GMT+08:00 Alfred Zhou <notifications@github.com>:
