### ISSUE TITLE
cnpm 4.2.0 安装其他模块的路径不对

### ISSUE THREAD

**Issue by milesxu** [cnpm/cnpm#93]
今天升级了cnpm 4.2.0，结果用cnpm升级其他模块一直不成功，看了操作记录才发现，所有更新的模块都被安装到`C:\Program Files\nodejs\lib\node_modules`下面了,之前一直是在`C:\Program Files\nodejs\node_modules`目录下的，所以更新了也找不到。
将cnpm换回3.4.1，更新就成功了。
环境：Windows 10 64bit，nodejs 5.8

**Comment by fengmk2** [comment]
@milesxu 你是说 -g 安装吧？

@dead-horse 看来 windows 下的 global dir 跟 linux 不一样。

**Comment by fengmk2** [comment]
@milesxu 你执行这个命令看看 `$ npm config get prefix -g` 和 `npm config get prefix`

https://github.com/npm/npm/wiki/Troubleshooting#a-brief-note-on-the-built-in-windows-configuration

**Comment by dead-horse** [comment]
是的.. 看来多了一个 lib..  windows 下是不用的

**Comment by alsotang** [comment]
腾讯这边全是 windows。。。

**Comment by milesxu** [comment]
@fengmk2 我已经运行了，你给的两个命令，我的环境下结果都是`C:\Program Files\nodejs`。我之前设置过npm的模块目录，也是因为cnpm默认安装到`Program Files`，而不是用户目录。
另外，我在ArchLinux上也有cnpm，最新版安装完成后，运行`npm outdated -g'，模块的wanted和latest全部变成了`linked`，而不是显示的版本号。不过current显示的版本号是最新的。

**Comment by dead-horse** [comment]
@alsotang 帮忙修一下？你那边 windows 多，哈哈

**Comment by alsotang** [comment]
。。我自己在这边用 mac 的

**Comment by dead-horse** [comment]
closed by cnpm/npminstall#57
