### ISSUE TITLE
4.2.0安装electron出错

### ISSUE THREAD

**Issue by caibirdme** [cnpm/cnpm#96]
`cnpm install electron-prebuilt --save-dev`
包可以正常安装上，但是运行时报错`... path.txt not found`
这个问题在0.37.2上有
当我切回0.36.11就OK了，不清楚是cnpm的问题还是electron的问题，但是electron目前也没这样的issue

**Comment by fengmk2** [comment]
我安装正常

![image](https://cloud.githubusercontent.com/assets/156269/14014296/b2378ea8-f1ec-11e5-866d-f972e4d5cd3e.png)
