### ISSUE TITLE
CNPM v4.2.0在Windows系统上工作不正常

### ISSUE THREAD

**Issue by panteng** [cnpm/cnpm#97]
Win10 x64
node v5.9.0
npm v3.8.3
cnpm v4.2.0

1. 使用`cnpm install xxx -g`安装全局模块有问题。比如全局安装gulp-cli后，在命令行中输入gulp -v，会提示找不到命令。

2. 使用`cnpm install xxx -d`时，控制台输入的信息与官方npm不一致，cnpm v4.2.0并没有把安装过程中的详细信息打印出来，而是显示下载文件大小和安装耗时。我不清楚cnpm的具体实现机制，但是我觉得尽可能让输出信息与官方npm一致是不是更妥当？

使用官方npm v3.8.3或者换回cnpm v3.4.1后则一切正常。

**Comment by alsotang** [comment]
cnpm 4.2 不是用的 npm 封装，而是用了 npminstall 这个库。所以你输入的 npm 参数，npminstall 不一定能接受。

在 2016年3月25日 下午11:01，Chris Pan <notifications@github.com>写道：

**Comment by panteng** [comment]
@alsotang 
感谢回复。
参数的问题ok，但是全局安装模块的问题是BUG吗，会在后续版本里修复吗？

**Comment by fengmk2** [comment]
`cnpm install xxx -d`

可以使用 `DEBUG=npminstall* cnpm install xxx` 代替

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/14057742/86c3a992-f344-11e5-84d4-5e926418528c.png)

我在非 windows 下是 ok 的， @panteng 你重新安装一下 cnpm，然后再尝试一次 -g 安装。

**Comment by fengmk2** [comment]
@panteng 应该是 https://github.com/cnpm/npminstall/issues/55 类似问题了。

**Comment by panteng** [comment]
@fengmk2 
感谢回复。
